### DISCUSSION TITLE
Log viewing when testing locally using Flyte-sandbox

### DISCUSSION THREAD

**Discussion by SandraGH5** [flyteorg/flyte#1285] [Q&A] [answered]
When testing locally using flyte-sandbox, FlyteConsole will show the link ``Kubernetes Logs (User)`` to view the logs. Once selected, it might require login details on the Kubernetes dashboard. 

```
kind: Deployment
apiVersion: apps/v1
metadata:
  name: kubernetes-dashboard
  namespace: kubernetes-dashboard
spec:
  template:
    spec:
      containers:
        - name: kubernetes-dashboard
          args:
            - --namespace=kubernetes-dashboard
            - --enable-insecure-login
            - --enable-skip-login
            - --disable-settings-authorizer
 ```
@jeevb 
Nicholas LoFaso
