### DISCUSSION TITLE
How do I increase the storage limit when using the sandbox?

### DISCUSSION THREAD

**Discussion by tekumara** [flyteorg/flyte#1342] [Q&A] [answered]
When using the sandbox my workflow is failing with:

```
Failed to GetPrevious data from outputDir ..... [LIMIT_EXCEEDED] limit exceeded. 4mb > 2mb
```

How can I increase the storage limit?

**Comment by tekumara** [comment, marked as answer]
I modified the flytepropeller configmap, and to storage.yaml added:

```
limits:
  maxDownloadMBs: 10
```

eg:
```
storage.yaml:                                             
----                                                      
storage:                                                  
  type: minio                                             
  connection:                                             
    access-key: minio                                     
    auth-type: accesskey                                  
    secret-key: miniostorage                              
    disable-ssl: true                                     
    endpoint: http://minio.flyte.svc.cluster.local:9000   
    region: us-east-1                                     
  container: "my-s3-bucket"                               
  limits:                                                 
    maxDownloadMBs: 10                                          
```

Then restarted flytepropeller (by killing the pod) which seemed to resolve the issue. 

Is there anyway to configure the sandbox, or default it, with a larger limit upfront?
