### DISCUSSION TITLE
Deploy Flyte on-prem configure local s3

### DISCUSSION THREAD

**Discussion by kumare3** [flyteorg/flyte#1712] [Q&A]
I'm try to deploy a test version of Flyte with the Helm chart, I'm not hosting on Google or Amazon, but I have got an S3 storage, so how can I try to customize the storage section with an individual endpoint for using S3: https://github.com/flyteorg/flyte/blob/master/charts/flyte/values.yaml#L473-L485
e.g. I need flags to setup the endpoint, s3 key and secret and enable HTTPS

**Comment by kumare3** [comment]
The storage configuration for Flyte backend is driven using the Config you pointed to. But, if you notice this is a template. We have simplified the installation on AWS and GCP, but you can ofcourse use the RAW configuration options to use non cloud storage backends. 

This can be seen in the template [here](https://github.com/flyteorg/flyte/blob/master/charts/flyte/templates/_helpers.tpl#L209-L212)

Thus, lets say you want to configure MINIO on-prem, then the configuration should look something like this


```
# If using similar to S3
  type: custom
  custom:
    container: <bucket-name>
    connection:
      access-key: minio
      auth-type: accesskey
      secret-key: miniostorage
      disable-ssl: true
      endpoint: http://minio....
      region: us-east-1
```
**Note** you still need to provide the region, as the minio is simply an emulation of S3 client.

If you want to provide even more raw configuration then refer to [stow](). this is the library Flyte uses to connect with the various backends

The configuration should look like
```
type: stow
stow:
    kind:<stow-kind>
    config:
       .... config keys
container: <bucket-name>
```

An example for configuring ``Azure`` - config similar to [here](https://github.com/graymeta/stow/blob/master/azure/config.go#L13-L16)
```
type: stow
stow:
   kind: azure
   config:
       account: <account>
       key: <key>
```
