### DISCUSSION TITLE
Setting up Auth for Flyte

### DISCUSSION THREAD

**Discussion by SandraGH5** [flyteorg/flyte#1890] [Q&A] [answered]
We're having trouble setting up auth for flyte. We're using Google SSO. We managed to get FlyteConsole browser login to work with Google but are struggling to get it to work for `flytectl` for both clients and in our CI pipelines.
We have tried the following `appAuth` config variants with respectively different problems:

**Variant 1** (As in this video from the docs):
```
  appAuth:
    thirdPartyConfig:
      flyteClient:
        clientId: flytectl
        redirectUri: https://localhost:53593/callback
        scopes:
          - offline
          - all
```
Result:
Running `flytectl` opens the browser at `https://our.great.domain.com/oauth2/authorize?client_id=flytectl&redirect_uri=http[…]Bfs8xq6Xp0bD1Nb6NWCdnQwsfsY&code_challenge_method=S256`
and shows:
```
{"error":"invalid_request","error_description":"The request is missing a required parameter, includes an invalid parameter value, includes a parameter more than once, or is otherwise malformed. The 'redirect_uri' parameter does not match any of the OAuth 2.0 Client's pre-registered redirect urls."}
```
This led us on the track of trying with an external auth server so Variant 2

**Variant 2** (added external auth server):

```
  appAuth:
    thirdPartyConfig:
      flyteClient:
        clientId: flytectl
        redirectUri: https://localhost:53593/callback
        scopes:
          - offline
          - all
    authServerType: External
    externalAuthServer:
      baseUrl: https://accounts.google.com
      metadataUrl: .well-known/openid-configuration
```
Result:
Running `flytectl` opens google accounts signing in browser with
```
Error 401: invalid_client
The OAuth client was not found.
```
This led us to believe that `clientId: flytectl` was a problem and we changed it to our google ClientID and to Variant 3.

**Variant 3** (A desperate hack):
```
  appAuth:
    thirdPartyConfig:
      flyteClient:
        clientId: 123456789-foobar.apps.googleusercontent.com
        redirectUri: https://localhost:53593/callback
        scopes:
          - profile # These scopes are allowed for Google, "offline" and "all" are not
          - openid
    authServerType: External
    externalAuthServer:
      baseUrl: https://accounts.google.com
      metadataUrl: .well-known/openid-configuration # Gotta set this or it defaults to ".well-known/oauth-authorization-
      server" which results in 404 with google
```
Result:
Running `flytectl` opens a browser window with Google login. After login the browser is redirected to `https://localhost:53593/callback?...` which for obvious reasons doesn't work.
The obvious culprit is the `redirectUri: https://localhost:53593/callback` up there. But before starting to deviate any further from the docs I thought it might be good to ask here.

@bimtauer
