### DISCUSSION TITLE
Sample Auth0 configuration

### DISCUSSION THREAD

**Discussion by wild-endeavor** [flyteorg/flyte#3638] [Deployment Tips & Tricks]
Just leaving this here in case it's helpful - sample auth0 configuration
```yaml
    # -- Authentication configuration
    auth:
      authorizedUris:
        # This should point at your public http Uri.
        - https://flyte-sandbox.xxx.io
        # This will be used by internal services in the same namespace as flyteadmin
        - http://flyteadmin:80
        # This will be used by internal services in the same cluster but different namespaces
        - http://flyteadmin.flyte.svc.cluster.local:80

      # Controls app authentication config
      appAuth:
        authServerType: External
        externalAuthServer:
          baseUrl: https://xxxx.us.auth0.com/
          metadataUrl: .well-known/openid-configuration
          allowedAudience: https://xxxx.us.auth0.com/api/v2/
        thirdPartyConfig:
          flyteClient:
            clientId: 456 #default: flytectl
            redirectUri: http://localhost:53593/callback
            audience: https://xxxx.us.auth0.com/api/v2/
            scopes:
              - read:client_grants
      # Controls user authentication
      userAuth:
        openId:
          baseUrl: https://xxxx.us.auth0.com/
          scopes:
            - profile
            - openid
            - offline_access
          #client ID from the Flyte console 
          clientId: 123
```
