### DISCUSSION TITLE
More customizable configuration of logging links

### DISCUSSION THREAD

**Discussion by fg91** [flyteorg/flyte#3666] [RFC Incubator]
I propose two enhancements that would make the configuration of logging links as documented [here](https://docs.flyte.org/projects/cookbook/en/latest/auto/deployment/configure_logging_links.html#how-to-configure) more powerful:

1. Logging links are only shown once the pod starts running while useful information could be provided before to users.

    A pod in `queued` status, no log links are shown:
    <img width="424" alt="Screenshot 2023-05-10 at 16 32 46" src="https://github.com/flyteorg/flyte/assets/36511035/2a57f580-e7f4-4cca-9379-a0bddc9f379c">

    Once the pod is running, we link to the pod's overview page in the GCP cloud console:
    <img width="414" alt="Screenshot 2023-05-10 at 16 42 18" src="https://github.com/flyteorg/flyte/assets/36511035/61ba2970-6e84-4578-9081-f13ac187a5d9">

    Even before a pod starts running, this page has useful information, e.g. in case the pod cannot be scheduled when the cluster cannot fulfil the task's resource requests.
    
    Having the ability to show some log links before the pod has started would give users not comfortable with `kubectl` an easy way to access this information directly from the Flyte console.
    
    This option could for instance be exposed like this:
    
    ```
    task_logs:
      plugins:
        logs:
          templates:
            - displayName: <name-to-show>
              templateUris:
                - "..."
              messageFormat: "json" # "unknown" | "csv" | "json"
              show_before_running: true
    ```

2. Providing more parameters for link templating:

    Currently [these](https://docs.flyte.org/projects/cookbook/en/latest/auto/deployment/configure_logging_links.html#id1) parameters can be used to template links.
    
    We would like to be able to add links to experiment tracking servers like Mlflow, Wandb, ...
    We typically add tags with e.g. the flyte task project, domain, version, and execution id (retrieved from the flyte context) to the runs in our experiment tracking server. If we had access to these values during link templating, we could provide links to the run/experiment in e.g. Wandb in the Flyte console. Currently we log this link and have to go to the stackdriver logs to retrieve it.
