### DISCUSSION TITLE
Help needed with deploying flyte in local kubernetes (rancher desktop)

### DISCUSSION THREAD

**Discussion by Yc-Chen** [flyteorg/flyte#3795] [Q&A] [answered]
Hi all,

I'm trying to deploy flyte locally as I do not want to use a remote S3 or SQL server. So I'm interested in using minio and locally deployed postgres. But I cannot get it running. This is what I see by accessing 'flyteconsole' pod:

![image](https://github.com/flyteorg/flyte/assets/3079912/51f9ffcb-fc54-4c88-beaa-5f5cf45d4047)

I can see from the logs that requests reached the flyteconsole pod, but I only see blank error page.

`flyteagent` is having lots of errors:
![image](https://github.com/flyteorg/flyte/assets/3079912/9212d7c9-21a5-44a6-a84b-7d4ba40ee719)

I deployed it using command ` helm install -n flyte -f values-flyte.yaml --create-namespace flyte flyte/flyte`. 

<details><summary>This part is an outdated question; I managed to get envoy working.</summary>
I noticed flyte-contour-envoy is not running properly. Could it be the reason?
[image](https://github.com/flyteorg/flyte/assets/3079912/252d9b6a-2972-4911-b65d-62ffeff96444)
  </details>

This is the tutorial that I followed: https://docs.flyte.org/en/v1.0.0/deployment/sandbox.html
I'm aware that this tutorial is outdated but I up-to-date one assumes a kubernetes on AWS and I don't have that.

**Comment by davidmirror-ops** [comment, marked as answer]
Hi @Yc-Chen, thanks for reporting and sorry for the struggles. We definitely need to improve the UX on non cloud K8s environments

What happens if you try to reach `http://localhost:30081/console`?

**Reply by Yc-Chen** [reply]
Wow...I really didn't know its running at 30081! I thought I need to explicitly forward the ports.

<img width="1503" alt="image" src="https://github.com/flyteorg/flyte/assets/3079912/a2406c01-4d97-41d7-a765-5a964c96538d">

**Reply by davidmirror-ops** [reply]
Interesting. Any chance you could share here what else you had to do -besides following that tutorial- to make it work?

**Reply by Yc-Chen** [reply]
Well...I think I didn't succeed completely yet though. The workflow is still stuck with the first step `get_data`. I modified the config a little based on a sandbox config I found in the repo. What would be config that I need to be able to run the same example [here](https://docs.flyte.org/projects/cookbook/en/latest/index.html#running-workflows-in-a-flyte-cluster)? I assume I do not need any plugins (yet)?

```yaml
# This is a sample configuration file for running single-binary Flyte locally against
# a sandbox.
admin:
  endpoint: localhost:57354
  insecure: true

catalog-cache:
  endpoint: localhost:8088
  insecure: true
  type: datacatalog

cluster_resources:
  standaloneDeployment: false
  templatePath: $HOME/.flyte/cluster-resource-templates

logger:
  show-source: true
  level: 6

propeller:
  create-flyteworkflow-crd: true
  kube-config: $HOME/.flyte/sandbox/kubeconfig
  rawoutput-prefix: s3://my-s3-bucket/data

server:
  kube-config: $HOME/.flyte/sandbox/kubeconfig

webhook:
  certDir: $HOME/.flyte/webhook-certs
  localCert: true
  secretName: flyte-sandbox-webhook-secret
  serviceName: flyte-sandbox-local
  servicePort: 9443

tasks:
  task-plugins:
    enabled-plugins:
      - container
      - sidecar
      - K8S-ARRAY
    default-for-task-types:
      - container: container
      - container_array: K8S-ARRAY

plugins:
  logs:
    kubernetes-enabled: true
    kubernetes-template-uri: http://localhost:30080/kubernetes-dashboard/#/log/{{.namespace }}/{{ .podName }}/pod?namespace={{ .namespace }}
    cloudwatch-enabled: false
    stackdriver-enabled: false
  k8s:
    default-env-vars:
    - FLYTE_AWS_ENDPOINT: http://flyte-sandbox-minio.flyte:9000
    - FLYTE_AWS_ACCESS_KEY_ID: minio
    - FLYTE_AWS_SECRET_ACCESS_KEY: miniostorage
  k8s-array:
    logs:
      config:
        kubernetes-enabled: true
        kubernetes-template-uri: http://localhost:30080/kubernetes-dashboard/#/log/{{.namespace }}/{{ .podName }}/pod?namespace={{ .namespace }}
        cloudwatch-enabled: false
        stackdriver-enabled: false

database:
  postgres:
    username: postgres
    password: postgres
    host: 127.0.0.1
    port: 30001
    dbname: flyte
    options: "sslmode=disable"

storage:
  type: stow
  stow:
    kind: s3
    config:
      region: us-east-1
      disable_ssl: true
      v2_signing: true
      endpoint: http://localhost:30002
      auth_type: accesskey
      access_key_id: minio
      secret_key: miniostorage
  container: my-s3-bucket

```
