### DISCUSSION TITLE
Can I deploy flyte using OSS, I think it's s3 compatible

### DISCUSSION THREAD

**Discussion by aixi** [flyteorg/flyte#4438] [Q&A] [answered]
https://www.alibabacloud.com/help/en/oss/developer-reference/compatibility-with-amazon-s3

**Comment by davidmirror-ops** [comment]
Hi @aixi 

We haven't tested it yet. It seems to support some of the base operations Flyte would perform against an S3 API endpoint:

```
"s3:DeleteObject*",
    "s3:GetObject*",
    "s3:PutObject*"
```
The exception is  `s3:ListBucket` which in Alibaba's OSS seem to be `GetBucket`.

Also, I'd say that Flyte can work with virtual hosted-style requests to S3, as flytepropeller uses a similar structure.


Nevertheless, if it works, it would still classify as a `custom`  storage backend for Flyte. To that end, users of the `flyte-core` chart have been successful using this configuration in the chart to consume a custom S3-compliant kv store:

```
  storage.yaml: | 
    storage:
      container: xxx
      stow:
        config:
          access_key_id: xxx
          auth_type: accesskey
          disable_ssl: false
          endpoint: xxx
          region: xxx
          secret_key: xxx
          v2_signing: false
        kind: s3
      type: stow
      enable-multicontainer: false
      limits:
        maxDownloadMBs: 10
```

Does that help?
