### ISSUE TITLE
[Core Feature] publish-flyte-workflow Github Action

### ISSUE THREAD

**Issue by EngHabu** [flyteorg/flyte#1017]
**Motivation: Why do you think this is important?**
Flyte encourages best practices around version tracking and immutability. One of the core tenants of doing so is a well integrated & seamless developer experience. Supporting github actions as a first class construct can lead to reiterating these good practices. After implementing a publishing Github Action, the developer's workflow can look something like:

In PR:
* Build docker image,
* Serialize Workflows & Tasks,
* Call publish-flyte-workflow (which in turn should just be a wrapper on top of flytectl) to register the workflows.

**Goal: What should the final outcome look like, ideally?**
A configurable action that takes in as params (my initial thought):
* URL of where flyte is (as well as whether to use secure or insecure connections)
* Project and domain to register against
* files to register (these may come as an output of a prior step? not sure)
* Client ID and Client Secret (optionally) to authenticate

**Comment by evalsocket** [comment]
Definition for github-action

```
name: 'flyte-github-action'
description: >
  Serialize and register flyte workflow
branding:
  icon: play
  color: blue
inputs:
  image:
    description: 'Docker image for running workflow'
    required: true
  outputi-dir:
    description: 'Output directory path'
    required: false
  serivce-account:
    description: 'Service account name for serialize'
    required: false
  action:
    description: 'Action name i.e. serialize, register'
    required: false
    default: serialize
  version:
    description: 'Version number of workflow'
    required: false
  output-dir-prefix:
    description: 'Output dir prefix like s3://my-s3-bucket/raw-data'
    required: false
  flyte-aws-endpoint:
    description: 'flyte aws endpoint'
    required: true
  flyte-aws-key:
    description: 'flyte-aws-key'
    required: true
  flyte-aws-secret:
    description: 'flyte aws secret'
    required: true
  flyte-host:
    description: 'flyte host url'
    required: true
  command:
    description: 'command'
    required: true
runs:
  using: 'node12'
  main: './dist/main.js'
```
