### ISSUE TITLE
[BUG] Flytectl get workflow with latest flag returns incomplete result

### ISSUE THREAD

**Issue by pmahindrakar-oss** [flyteorg/flyte#1053]
**Describe the bug**

* When calling the get workflow with --latest flag return only the identity object when dumping the yaml/json data 

`flytectl get workflow -d development -p flytectldemo core.control_flow.run_merge_sort.merge_sort --latest -o yaml`

**Output**
```
{"json":{"src":"workflow.go:89"},"level":"debug","msg":"Retrieved 1 workflow","ts":"2021-05-26T13:36:50+05:30"}
closure:
  createdAt: "2021-05-25T10:33:03.302078Z"
id:
  domain: development
  name: core.control_flow.run_merge_sort.merge_sort
  project: flytectldemo
  resourceType: WORKFLOW
  version: v1
```

* When calling the same workflow with --version  v1  which is the latest version then it returns the complete data

`flytectl get workflow -d development -p flytectldemo core.control_flow.run_merge_sort.merge_sort --version v1 -o yaml`

**Output**
```
{"json":{"src":"workflow.go:89"},"level":"debug","msg":"Retrieved 1 workflow","ts":"2021-05-26T13:36:59+05:30"}
closure:
  compiledWorkflow:
    primary:
      connections:
        downstream:
          node-0:
            ids:
            - end-node
            - node-0-branchn0
            - node-0-branchn1
          start-node:
            ids:
            - node-0
            - node-0-branchn0
            - node-0-branchn1
.........
```

**Expected behavior**
The get --latest and get --version o/p should return the same structure of the data 

**[Optional] Additional context**
***To Reproduce***
As provided above

***Screenshots***

cc : @kumare3 @katrogan
