### ISSUE TITLE
Flyteadmin gets stuck in waiting if db host or port changes.

### ISSUE THREAD

**Issue by ajsalow** [flyteorg/flyte#1142]
If I change the hostname of the  my postgres instance in the helm Values.yaml

```yaml
db:
  database: {}
    port: 5432
    username: postgres
    host: my-postgres-host
    dbname: flyte
    passwordPath: /etc/db/pass.txt
```

admin doesn't finish initializing because it is waiting for the host "postgres" to be ready.
`until pg_isready -h postgres -p 5432; do echo waiting for database; sleep 2; done;`

The deployment should reference the helm values here
`until pg_isready -h {{ .Values.db.datbase.host }} -p {{ .Values.db.database.port }}; do echo waiting for database; sleep 2; done;`
