### ISSUE TITLE
[BUG] Task fails with error: `containers with unready status: [main]|failed to reserve container name`

### ISSUE THREAD

**Issue by jeevb** [flyteorg/flyte#1234]
**Describe the bug**
We had a rare failure where a task (and consequently the workflow) failed with the following error:
```
containers with unready status: [main]|failed to reserve container name "main_f76be7b00ec9b4348871-n1-0_pineapple-development_987b2aa9-b537-4038-9884-8d2bc413762a_0": name "main_f76be7b00ec9b4348871-n1-0_pineapple-development_987b2aa9-b537-4038-9884-8d2bc413762a_0" is reserved for "6678ab271c041304d4a91e8e219dca896388098ec8a258dc49f4f9942296f669"
```

**Expected behavior**
Flytepropeller handles these likely transient issues gracefully:

Relevant issue: https://github.com/containerd/containerd/issues/4604
See this [comment](https://github.com/containerd/containerd/issues/4604#issuecomment-751519757):
> Eventually, kubelet is able to resolve this issue without manual intervention, however, it is significantly slowing the deployment of new images during the release (extra 2-3 minutes to resolve name conflicts).

It is possible that Flyte might be catching and failing on the error too fast before kubelet can resolve this issue on its own. Flyte might need to wait and let this issue resolve, possibly with some reasonable timeout.

**[Optional] Additional context**
***To Reproduce***
1. 
2. 

***Screenshots***

**Comment by kumare3** [comment]
This will need a change in this code - https://github.com/flyteorg/flyteplugins/blob/master/go/tasks/pluginmachinery/flytek8s/pod_helper.go#L114

**Comment by jeevb** [comment]
Status for affected pod:
```
status:
  conditions:
  - lastProbeTime: null
    lastTransitionTime: "2021-07-15T20:00:27Z"
    status: "True"
    type: Initialized
  - lastProbeTime: null
    lastTransitionTime: "2021-07-15T20:00:27Z"
    message: 'containers with unready status: [main]'
    reason: ContainersNotReady
    status: "False"
    type: Ready
  - lastProbeTime: null
    lastTransitionTime: "2021-07-15T20:00:27Z"
    message: 'containers with unready status: [main]'
    reason: ContainersNotReady
    status: "False"
    type: ContainersReady
  - lastProbeTime: null
    lastTransitionTime: "2021-07-15T20:00:27Z"
    status: "True"
    type: PodScheduled
  containerStatuses:
  - containerID: containerd://b8102271f17f23920f3c1d6eedfaabbaf35f020b88df37850239a9d27af74445
    image: gcr.io/freenome-build-dev/jjxiao/pineapple:c7812050315c44001ca3d56f6884ff665a031b0dba4bab81b9bdd1a35874ab9d
    imageID: gcr.io/freenome-build-dev/jjxiao/pineapple@sha256:c7812050315c44001ca3d56f6884ff665a031b0dba4bab81b9bdd1a35874ab9d
    lastState:
      terminated:
        containerID: containerd://b8102271f17f23920f3c1d6eedfaabbaf35f020b88df37850239a9d27af74445
        exitCode: 0
        finishedAt: null
        startedAt: null
    name: main
    ready: false
    restartCount: 0
    started: false
    state:
      waiting:
        message: 'failed to reserve container name "main_fqsqptwy-ftkcixqy-0_pineapple-development_b677f350-5460-40e6-ad51-899bc031131b_0":
          name "main_fqsqptwy-ftkcixqy-0_pineapple-development_b677f350-5460-40e6-ad51-899bc031131b_0"
          is reserved for "b8102271f17f23920f3c1d6eedfaabbaf35f020b88df37850239a9d27af74445"'
        reason: CreateContainerError
  hostIP: 172.16.192.111
  phase: Failed
  podIP: 10.192.116.6
  podIPs:
  - ip: 10.192.116.6
  qosClass: Guaranteed
  startTime: "2021-07-15T20:00:27Z"
  ```

**Comment by jeevb** [comment]
Possibly relevant: https://bugzilla.redhat.com/show_bug.cgi?id=1785399

**Comment by jeevb** [comment]
@kumare3 @EngHabu: Which of this do you think makes more sense for this:
1. Mark `CreateContainerError` as retryable failure if message contains `failed to reserve container name`. Would propeller delete and requeue if this is the case?
2. Mark as initializing, but with a timeout of 5 mins (should this be configurable?). If timeout is exceeded, mark as failed.

**Comment by EngHabu** [comment]
Apologies for the delay... was still catching up...
If I understand the linked issue correctly, this pod will move "back" from a `Failed` Phase to `Running` when CRI-O fixes the name issue? this is disturbing... breaks the fundamental assumption that `Succeeded` and `Failed` are terminal phases for a Pod... pretty bad design...

RE: the proposed solutions:
1. Yes, but given the description of the bug, that might actually make things worse if nodes are under load?
2. So the Pod will move from `Pending` to `Failed` if so, the idea would be to keep the task in "Initializing" phase, if it was already in initializing, if we see the Pod is `Failed` and the message says `failed to reserve container name` and wait some minutes before declaring it as failure?

**Comment by jeevb** [comment]
No worries, thanks for responding @EngHabu.

It's not clear to me that it's in a `Failed` phase. I believe it's still in the `Pending` phase. I can check, but this is pretty hard to reproduce.

1. That is fair. But there is the possibility that it will reschedule on a less loaded node.
2. That's right. The comments in the linked issue above seem to suggest that it resolves in 2-3 mins on its own. The issue is with kubelet retrying the pod creation due to some communication failure, after the runtime has already received the request and created it.

**Comment by EngHabu** [comment]
The pod status [here](https://github.com/flyteorg/flyte/issues/1234#issuecomment-881000387) represents a Pod that actually failed because of that issue? like kubelet tried and eventually gave up or something?

so we hit this line: https://github.com/flyteorg/flyteplugins/blob/master/go/tasks/pluginmachinery/flytek8s/pod_helper.go#L185 ic ic... I think I'm now caught up :-) 

So it looks like what happened is that yeah we hit that line, we marked the task as failed but the Pod never recovered and it actually moved to Failed phase (which I certainly hope is terminal. i.e. once it hits that it will never go back to running)... if that's the case then I do like your second option because it means kubelet may eventually give up and actually mark the Pod as failed and when it does, we will just read it as such and mark the task as failed subsequently...

The timeline as I understand it:

1. The Pod is created
2. The Pod moves to Pending phase
3. The Pod remains in Pending state with a container in Waiting state and hitting that "failed to reserve container name" issue
4. <Flyte detects that and declares the task has failed>
5a. Sometimes kubelet <> CRI-O eventually works things out and the Pod moves to `Running`
5b. Other times kubelet gives up and the Pod moves to `Failed`

Did I get that right?

**Comment by jeevb** [comment]
> The pod status here represents a Pod that actually failed because of that issue? like kubelet tried and eventually gave up or something?
I don't think we gave kubelet enough time to resolve this. The task was marked as failed and the workflow short-circuited without retries.

<img width="2560" alt="Screen Shot 2021-08-06 at 10 28 18 PM" src="https://user-images.githubusercontent.com/10869815/128589213-6f338374-d109-4f1c-818e-19c738e06e60.png">

I think your breakdown is correct per my understanding.

**Comment by jeevb** [comment]
Here's another one that appears to either be a transient error or a system-level retryable error:
```
containers with unready status: [main]|context deadline exceeded
```

**Comment by jeevb** [comment]
Looks like others are seeing this issue as well: https://serverfault.com/q/1036683

**Comment by jeevb** [comment]
@EngHabu @kumare3: Do we have consensus on the path forward for this?

**Comment by jeevb** [comment]
More weirdness on stress testing (not related to Flyte, but to failure modes in GKE under load):
```
status:
  conditions:
  - lastProbeTime: null
    lastTransitionTime: "2021-08-17T05:16:01Z"
    status: "True"
    type: Initialized
  - lastProbeTime: null
    lastTransitionTime: "2021-08-17T05:16:01Z"
    message: 'containers with unready status: [main]'
    reason: ContainersNotReady
    status: "False"
    type: Ready
  - lastProbeTime: null
    lastTransitionTime: "2021-08-17T05:16:01Z"
    message: 'containers with unready status: [main]'
    reason: ContainersNotReady
    status: "False"
    type: ContainersReady
  - lastProbeTime: null
    lastTransitionTime: "2021-08-17T05:16:01Z"
    status: "True"
    type: PodScheduled
  containerStatuses:
  - containerID: containerd://c78d489d78796f4e79aa57de5524db44ffc296589adff8362f7ff033e1536763
    image: gcr.io/freenome-build-dev/jeev/pineapple:jeev-make-targets-7446fb30cb9b
    imageID: gcr.io/freenome-build-dev/jeev/pineapple@sha256:c3e6c03b50837bd5a5b7a644a035dac5526142e127a10263f1ac6fae8f1a2d93
    lastState:
      terminated:
        containerID: containerd://c78d489d78796f4e79aa57de5524db44ffc296589adff8362f7ff033e1536763
        exitCode: 0
        finishedAt: null
        startedAt: null
    name: main
    ready: false
    restartCount: 0
    started: false
    state:
      waiting:
        message: context deadline exceeded
        reason: CreateContainerError
  hostIP: 172.16.192.170
  phase: Running
  podIP: 10.192.43.5
  podIPs:
  - ip: 10.192.43.5
  qosClass: Guaranteed
  startTime: "2021-08-17T05:16:01Z"
  ```
