### ISSUE TITLE
[Flytectl Feature] Register/share flyte workflows using github release

### ISSUE THREAD

**Issue by evalsocket** [flyteorg/flyte#1267]
**Describe the feature/command for flytectl**

### Requirement for sharing the flyte workflow  (Producer)
- User should add a `.flyte.yaml` in their root directory
```
name: flytesnacks
workflows:
- name: core
  release_name: core_example.tgz
  custome_url: https://s3.aws.com/???? #only used for private workflow and can be used for any flytehub...In the case of GitHub, we can use GitHub release 
```
- Serialize proto in GitHub action on the new tag 
- Publish tar of serialize proto in GitHub release 

### New command in flytectl (Consumer)
```bash
flytectl register workflow flyteorg/flytesnacks core 
flytectl register workflow evalsocket/flyte_ml mnist --version=v1.0.0 
flytectl register workflow flyteorg/flytesnacks list
```

**Provide a possible output or ux example**
A clear and concise description of what you want to happen or achieve.
