### ISSUE TITLE
[BUG] flytectl execution spec generation writes datetime default in failing format 

### ISSUE THREAD

**Issue by vglocus** [flyteorg/flyte#1399]
**Describe the bug**
I have a sample workflow `demo-1.example` with a datetime parameter

```
closure:
  createdAt: "2021-08-30T10:03:07.857772Z"
  expectedInputs:
    parameters:
      DATETIME_PARAMETER:
        required: true
        var:
          type:
            simple: DATETIME
```
 
Generating an execution spec by:
 
`flytectl get launchplans -p demo-1 -d development --latest -o yaml demo-1.example --execFile execution_spec.yaml`

The execution spec comes out looking like:

```
iamRoleARN: ""
inputs:
    DATETIME_PARAMETER:
        seconds: 1630424397
        nanos: 684703000
kubeServiceAcct: ""
targetDomain: ""
targetProject: ""
version: 387a530905234e12e772ee1ef99cb3c7de52cf29
workflow: demo-1.example
```

The output format corresponds to protobuffs representation and is not executable by `flytectl create execution --execFile execution_spec.yaml -p demo-1 -d development`

This fails with

```
Error: failed to parse Datetime in RFC3339 format: parsing time "map[nanos:6.84703e+08 seconds:1.630424397e+09]" as "2006-01-02T15:04:05Z07:00": cannot parse "map[nanos:6.84703e+08 seconds:1.630424397e+09]" as "2006"
```

**Expected behavior**
The default value provided by `get launchplan --execFile ` is is a format that is understandable by `create exection`

Generated file should be on the below format which `flytectl create execution` can parse.

```
iamRoleARN: ""
inputs:
    DATETIME_PARAMETER: 2021-08-31T15:41:59.981428Z
kubeServiceAcct: ""
targetDomain: ""
targetProject: ""
version: 387a530905234e12e772ee1ef99cb3c7de52cf29
workflow: demo-1.example
```

**[Optional] Additional context**
***To Reproduce***
1. Register a launchplan with datetime input
2. Generate execution specification like above

***Code analysis***

In `ParamMapForWorkflow cmd/get/execution_util.go:119` a default value is outputted using `ExtractFromLiteral github.com/flyteorg/flyteidl@v0.19.24/clients/go/coreutils/extract_literal.go:30` which will

```
case *core.Primitive_Datetime:
    scalarPrimitiveDateTime := scalarPrimitive.Datetime
    return scalarPrimitiveDateTime, nil
```
(github.com/flyteorg/flyteidl@v0.19.24/clients/go/coreutils/extract_literal.go:48-50)

where  Datetime here is a protobuff timestamp

```
type Primitive_Datetime struct {
	Datetime *timestamp.Timestamp `protobuf:"bytes,5,opt,name=datetime,proto3,oneof"`
}
```
(github.com/flyteorg/flyteidl@v0.19.24/gen/pb-go/flyteidl/core/literals.pb.go:89-91)

This value is added as is to the paramMap (cmd/get/execution_util.go:138-143). 

One possible solution would be to run [Timestamp.AsTime](https://pkg.go.dev/google.golang.org/protobuf/types/known/timestamppb#Timestamp.AsTime) on the value which would be outputted as a valid string (used to generate the expected result above).
