### ISSUE TITLE
[BUG] SignedURL config in flyteadmin on GCP deployments should not be necessary

### ISSUE THREAD

**Issue by katrogan** [flyteorg/flyte#1738]
### Describe the bug

User reports that without setting the signed url bit of the remote data config in flyteadmin, e.g.:

```
# Adds the remoteData config setting
  remoteData:
    remoteData:
      region:
      scheme: "gcs"
      signedUrls:
        durationMinutes: 3
```

admin deployments on GCP cause console actions such as launch, relaunch, etc to fail because of this offending line

```
signedURLDuration := time.Minute * time.Duration(cfg.SignedURLDurationMinutes)
		return &remoteDataHandler{
			remoteURL: implementations.NewGCPRemoteURL(cfg.SigningPrincipal, signedURLDuration),
		}
```

 

### Expected behavior

SignedURLs aren't used for GCP deployments. This duration in the config should not be required for things to work.

### Additional context to reproduce

slack thread https://flyte-org.slack.com/archives/C02D2EQ3XCG/p1634900482014500

### Are you sure this issue hasn't been raised already?

- [X] Yes

### Have you read the Code of Conduct?

- [X] Yes
