### ISSUE TITLE
[FlyteCTL Feature] Ability to update project labels

### ISSUE THREAD

**Issue by pradithya** [flyteorg/flyte#1873]
### Describe the feature/command for FlyteCTL

Add support for labels in `flytectl create project` command. 

### Provide a possible output or UX example

Inline Update
```
 bin/flytectl update project --name flytesnacks --id flytesnacks --labels app=flyte
```

Using yaml
```
 bin/flytectl update project --file project.yaml
```

with project.yaml:
```
    id: "project-unique-id"
    name: "Name"
    labels:
     app: flyte
```

Related issue: https://github.com/flyteorg/flyte/issues/1620 

### Are you sure this issue hasn't been raised already?

- [X] Yes

### Have you read the Code of Conduct?

- [X] Yes
