### ISSUE TITLE
[Core feature] Improved system-wide Default Pod configuration

### ISSUE THREAD

**Issue by kumare3** [flyteorg/flyte#2069]
### Motivation: Why do you think this is important?

It is often required that for specific deployment of Flyte, platform admins want to control certain properties on the pod as a default. For example, some organizations want default annotations, labels, some want default securitycontext and some others want to use hostnetworking mode. Today this is handled using one-off configs in [FlytePlugins.pluginmachinery](https://github.com/flyteorg/flyteplugins/blob/master/go/tasks/pluginmachinery/flytek8s/config/config.go#L65-L141)

### Goal: What should the final outcome look like, ideally?

Ideally, platform admins should be able to configure the pod defaults without making code changes as requirements change. Also it should be possible to have pod defaults per-namespace. This would allow greater customization as well as the need for mutating webhooks can be minimized.

### Describe alternatives you've considered 

Pods are mutated or keep adding new flags.

###  Propose: Link/Inline OR Additional context 

Flytepropeller deployment for sharding now uses [PodTemplates](https://kubernetes.io/docs/concepts/workloads/pods/#pod-templates) to manage the individual propeller pods. We can leverage this technique to manage default pod settings for all pods launched by flyte. Furthermore we could allow this system to extend beyond a single default to a per namespace default. One caveats with this approach is that it would render existing configurations useless or confusing. We will support it in a backwards compatible way. For example, if a pod-template is available then it will be first applied and any config settings will override those values. A recommendation would be for all admins, to stop using the one-off configurations.

### Are you sure this issue hasn't been raised already?

- [X] Yes

### Have you read the Code of Conduct?

- [X] Yes

**Comment by kumare3** [comment]
cc @jeevb / @veggiemonk / @akumor / @akhurana001 / @jonbender-stripe

**Comment by veggiemonk** [comment]
What is the granularity level of the customization of the podTemplate? Per task? Per workflow?

**Comment by jeevb** [comment]
Per-namespace or project/domain it looks like. This is just for the default pod config, I think.

**Comment by kumare3** [comment]
@jeevb / @veggiemonk yes - per project/domain. Actually we will have to do per namespace, i.e., in many cases organizations use Flyte in single namespace per domain mode. At the moment I am not sure if we can add templates per project-domain within one namespace.

**Comment by frsann** [comment]
Adding this issue for reference: https://github.com/flyteorg/flyte/issues/1592

**Comment by hamersaw** [comment]
Currently the one-off [k8s plugin config](https://github.com/flyteorg/flyteplugins/blob/558239088a09ca28aece2cc5db9e62d720ed3d1f/go/tasks/pluginmachinery/flytek8s/config/config.go#L65-L141) works by defaulting every pod, rather than by project/domain or namespace (unless propeller is started limited on namespace with a different config).

How does the configuration look for configuring based on namespace? In the [k8s plugin conig](https://github.com/flyteorg/flyteplugins/blob/558239088a09ca28aece2cc5db9e62d720ed3d1f/go/tasks/pluginmachinery/flytek8s/config/config.go#L64) we can add a defaultPodTemplate variable that is used **if the PodTemplate resource exists**. The namespace for this PodTemplate will coincide with the pod being created? For example, flyte components are all deployed in the "flyte" namespace. A workflow executed in the "flytesnacks-development" namespace will check that namespace for the defaultPodTemplate. Alternatively a workflow in the "flytesnacks-production" namespace will require a separate PodTemplate. If they don't exist, then we default to an empty PodSpec and in both cases override any parameters with the existing k8s configuration.

Additionally, we could offer a fallback, if the "flytesnacks-development" defaultPodTemplate name doesn't exist, we check the namespace of the FlytePropeller instance. So if the k8s configuration is something like below, a workflow in the "flytesnacks-development" namespace uses the flyte pod template and the "flytesnacks-production" workflow uses the flytesnacks-production template?

    apiVersion: v1
    kind: PodTemplate
    metadata:
      name: defaultPodTemplateName
      namespace: flyte
    template:
      ... // redacted
    ---
      apiVersion: v1
    kind: PodTemplate
    metadata:
      name: defaultPodTemplateName
      namespace: flytesnacks-production
    template:
      ... // redacted

This is always a trade-off on unwanted or unexpected behavior. Users mock something up in development and expect things to work in production but we need to ensure the PodTemplate is deployed in both. Defining a single PodTemplate for all namespaces is a more simple solution, but I'm not sure it offers the configurability that this issue envisions. Although this is how the current implementation for one-off pod configuration is currently implemented.

**Comment by katrogan** [comment]
we could consider adding a PodTemplate as a new [configurable matchable resource](https://docs.flyte.org/en/latest/deployment/cluster_config/general.html#deployment-cluster-config-general) if we wanted per-namespace overrides but not sure if a message this large is something we necessarily want to capture inline in the workflow CRD

**Comment by kumare3** [comment]
I think this is becoming a priority and I think one of us will work on this ASAP. 

What if we do simple Flyte namespace global
Pod template first and then add support for per namespace/ per project-domain default?

Because some folks don't use multiple namespaces.

**Comment by hamersaw** [comment]
@kumare3 @EngHabu - Running into a few issues with the default pod template. K8s requires a PodTemplate has least one container. So we have a few options. We can add a "noop" container with something like this:
```
apiVersion: v1
kind: PodTemplate
metadata:
  name: flyte-default-template
  namespace: flyte
template:
  metadata:
  spec:
    containers:
      - name: noop
        image: docker.io/rwgrim/docker-noop
    hostNetwork: true
    securityContext:
      runAsNonRoot: true
```
and then either (1) remove the container when building the pod with flyteplugins or (2) leave the noop (it's like a 800Kb image that does nothing). Another idea is to implement this by defining a [PodSpec](https://pkg.go.dev/k8s.io/api/core/v1#PodSpec) in the k8s plugin configuration rather than [individual PodSpec fields](https://github.com/flyteorg/flyteplugins/blob/5a80da6b9d9a6fbca413148aaf712e5615be6e52/go/tasks/pluginmachinery/flytek8s/config/config.go#L135-L150). So the k8s plugin configuration can be something like:
```
plugins:
  # All k8s plugins default configuration
  k8s:
    inject-finalizer: true
    default-annotations:
      - annotationKey1: annotationValue1
    resource-tolerations:
      nvidia.com/gpu:
        key: flyte/gpu
        value: dedicated
        operator: Equal
        effect: NoSchedule
    co-pilot:
      name: "flyte-copilot-"
      image: "ghcr.io/flyteorg/flytecopilot:v0.0.15"
      start-timeout: "5s"
    default-pod-spec:
      hostNetwork: true
      securityContext:
        runAsNonRoot: true
        // etc ...
```
This opens all PodSpec fields and we can stop adding one-off additions. The default-pod-spec is used as a base layer for all k8s resources. Fields set as part of the container or sidecar plugins will override them, and fields explicitly set in existing k8s plugin configuration will override as well.

Thoughts? Any input is welcome.
