### ISSUE TITLE
[Housekeeping] Release rollback

### ISSUE THREAD

**Issue by evalsocket** [flyteorg/flyte#2080]
### Describe the issue

Improvements around Flyte release rollback 

- [x] Force flytectl to use `latest version sha`  for sandbox docker image in place of `dind` (https://github.com/flyteorg/flytectl/pull/266)
- [x] Write a documentation for rollback helm manually
- [ ] Stop publishing `latest` and `dind` tag for sandbox (https://github.com/flyteorg/flyte/pull/2085)
- [ ] Verify helm upgrade process for beta release
- [x] Create Github workflow for all component to create patch release (https://github.com/flyteorg/flyteadmin/pull/327, https://github.com/flyteorg/flytepropeller/pull/387)
- [x] Add Upgrade Test in CI with sandbox (Already exist but currrently it's in broken stage)
- [ ] https://github.com/flyteorg/flyte/issues/2077 (https://github.com/flyteorg/flyteadmin/pull/329)

### What if we do not do this?

NA

### Are you sure this issue hasn't been raised already?

- [X] Yes

### Have you read the Code of Conduct?

- [X] Yes

**Comment by evalsocket** [comment]
cc: @EngHabu

**Comment by evalsocket** [comment]
@EngHabu 

# Rollback Helm Release

- Clone `flyte` Repo
- checkout `gh-pages`
- Remove helm package for flyte-core `rm flyte-core-v0.19.0.tgz`
- Remove helm package for flyte `rm flyte-v0.19.0.tgz`
- Remove version entry in `index.yml` for both chart. Entry look like this 
```yaml 
  - apiVersion: v2
    created: "2022-01-19T03:23:18.295085027Z"
    dependencies:
    - alias: flyte
      name: flyte-core
      repository: file://../flyte-core
      version: v0.19.1
    - condition: contour.enabled
      name: contour
      repository: https://charts.bitnami.com/bitnami
      version: 4.1.2
    - alias: sparkoperator
      condition: sparkoperator.enabled
      name: spark-operator
      repository: https://googlecloudplatform.github.io/spark-on-k8s-operator
      version: 1.0.6
    - condition: kubernetes-dashboard.enabled
      name: kubernetes-dashboard
      repository: https://kubernetes.github.io/dashboard/
      version: 4.0.2
    description: A Helm chart for Flyte Sandbox
    digest: 6c207f4545311aa6d4d249ec536e6a6f37d20bbbfc327fa761baf1ad68a5541b
    name: flyte
    type: application
    urls:
    - https://flyteorg.github.io/flyte/flyte-v0.19.1.tgz
    version: v0.19.1
  - apiVersion: v2
    created: "2022-01-19T03:23:18.278383346Z"
    dependencies:
    - alias: flyte
      name: flyte-core
      repository: file://../flyte-core
      version: v0.19.0
    - condition: contour.enabled
      name: contour
      repository: https://charts.bitnami.com/bitnami
      version: 4.1.2
    - alias: sparkoperator
      condition: sparkoperator.enabled
      name: spark-operator
      repository: https://googlecloudplatform.github.io/spark-on-k8s-operator
      version: 1.0.6
    - condition: kubernetes-dashboard.enabled
      name: kubernetes-dashboard
      repository: https://kubernetes.github.io/dashboard/
      version: 4.0.2
    description: A Helm chart for Flyte Sandbox
    digest: e60e7ffe3e4491714db0fdc324722f2282e5127742bebb8b249adc66bc25cd4c
    name: flyte
    type: application
    urls:
    - https://flyteorg.github.io/flyte/flyte-v0.19.0.tgz
    version: v0.19.0
```
- Commit the changes in gh-pages directly/via PR
