### ISSUE TITLE
[BUG] Enable k8s array plugin and aws batch plugin simultaneously

### ISSUE THREAD

**Issue by hamersaw** [flyteorg/flyte#2205]
### Describe the bug

The k8s array plugin and aws batch plugin both declare themselves as the default plugin for the task type "container_array". Therefore, a FlytePropeller instance is unable to enable both of these plugins simultaneously.

### Expected behavior

A Flyte deployment should be able to support the k8s array plugin and AWS batch plugin simultaneously.

### Additional context to reproduce

The following FlytePropeller task configuration:
```
tasks:
  task-plugins:
    enabled-plugins:
      - aws_array
      - K8S-ARRAY
    default-for-task-types:
      - container_array: K8S-ARRAY
```
causes this error:
`Error: Error running FlytePropeller.: TaskType [container_array] has multiple default handlers specified: [aws_array] and [k8s-array]`

### Are you sure this issue hasn't been raised already?

- [X] Yes

### Have you read the Code of Conduct?

- [X] Yes
