### ISSUE TITLE
[Docs] Using a default PodTemplate to configure k8s Pods

### ISSUE THREAD

**Issue by hamersaw** [flyteorg/flyte#2616]
### Description

FlytePropeller supports configuration of all k8s Pods executed using the Pod plugin by creating a default PodTemplate with [this PR](https://github.com/flyteorg/flytepropeller/pull/404). This functionality requires the [default-pod-template-name](https://docs.flyte.org/en/latest/deployment/cluster_config/flytepropeller_config.html#default-pod-template-name-string) configuration option to be set in FlytePropeller.

When executing, FlytePropeller attempts to use the PodTemplate in the namespace that the Pod will be created in (ex. by default a pod in the project `flytesnacks` and domain `development` will look for a PodTemplate in the `flytesnacks-development` namespace). If that PodTemplate does not exist, it then attempts to find on in the namespace that FlytePropeller runs in. It is important to note that this PodTemplate is used as the base Pod. All other configuration options (ex. task specific resources, Pod plugin configuration options, etc) will override the values set in the PodTemplate.

The only thing to note when setting up this configuration is that k8s requires PodTemplates to have a container set. In the implementation we override this value, because Flyte requires certain containers to be running. So when defining the default PodTemplates you may set a `noop` container by doing something like:
```
apiVersion: v1
kind: PodTemplate
metadata:
  name: flyte-default-template
  namespace: flyte
template:
  metadata:
  spec:
    containers:
      - name: noop
        image: [docker.io/rwgrim/docker-noop](http://docker.io/rwgrim/docker-noop)
```
Again, this container is never initialized or executed, rather it serves as a placeholder to validate the PodTemplate.

### Are you sure this issue hasn't been raised already?

- [X] Yes

### Have you read the Code of Conduct?

- [X] Yes
