### ISSUE TITLE
[BUG] Flyteadmin authzserver rejects Basic Authorization header - ClientSecret auth flow with SynchronousFlyteClient fails

### ISSUE THREAD

**Issue by bimtauer** [flyteorg/flyte#2849]
### Describe the bug

In order to do some automated integration testing from within github actions we're trying to use flytekits `SynchronousFlyteClient` with "ClientSecret" to launch executions and check results.

flytekit correctly parses the authType setting and tries to put together an HTTP Basic auth request (see [code](https://github.com/flyteorg/flytekit/blob/master/flytekit/clients/raw.py#L222)). 
As part of that it generates a basic authorization header ([code](https://github.com/flyteorg/flytekit/blob/master/flytekit/clients/raw.py#L247)) with the typical content: `Authorization: Basic <base64encoded-clientId:clientSecret>`. So far all is good and in line with [RFC6749](https://www.rfc-editor.org/rfc/rfc6749#section-2.3). 

**Weird thing is that Flyteadmin's authzserver doesn't like responding to requests with an authorization header set.** I've verified manually that the following fails:
```shell
$ curl -X POST my.host.com/oauth2/token -H "Authorization: Basic <base64encodedcreds>" -H "Accept: application/json" -H "Cache-Control: no-cache" -H "Content-Type: application/x-www-form-urlencoded" -d "grant_type=client_credentials&scope=access_token"

> {"error":"invalid_client","error_description":"Client authentication failed (e.g., unknown client, no client authentication included, or unsupported authentication method)."}
```
While sending `clientId` and `clientSecret` as parameters works:
```shell
$ curl -s -X POST my.host.com/oauth2/token -H "Accept: application/json" -H "Cache-Control: no-cache" -H "Content-Type: application/x-www-form-urlencoded" -d "grant_type=client_credentials&scope=access_token&client_id=my-client&client_secret=supersecret"

> {"access_token":"ey....."}
```
The fact that the latter works should mean that the auth server setup & credentials etc are correct and working. Afaik flytekit is doing the right thing by assembling the Authorization header - sending credentials as parameters is discouraged. Still that seems to break here and I spent an entire day unsuccessfully debugging this. 

I've tried hacky workarounds such as setting `authType: ExternalCommand` and trying to pass my working curl command but that doesn't seem the right way. 

### Expected behavior

I'd expect that flytekit completes the client secret flow and gets a Bearer token back that it can then use. 

### Additional context to reproduce

Make sure the following are set in your config:

_test-config.yaml_
```yaml
admin:
  insecure: false
  authType: ClientSecret
  clientId: my-client
  clientSecretLocation: /etc/secrets/client_secret
```
`/etc/secrets/client_secret` should contain your client secret

Run the following:
```python
from flytekit.configuration import PlatformConfig
from flytekit.clients.friendly import SynchronousFlyteClient

cfg = PlatformConfig.auto(config_file="test-config.yaml")
client = SynchronousFlyteClient(cfg)
client.list_projects_paginated() # Send some request - should result in failure
```

In our case, the client is set up like this in the `server.yaml` settings:
```yaml
auth:
  appAuth:
    selfAuthServer:
      staticClients:
        - my-client:
            id: my-client
            client_secret: <base64encoded-bcrypt-hash>
            scopes:
              - access_token
              - offline
              - all
            grant_types:
              - client_credentials
            response_types:
              - token
```

### Are you sure this issue hasn't been raised already?

- [X] Yes

### Have you read the Code of Conduct?

- [X] Yes

**Comment by wild-endeavor** [comment]
Actually I'm having trouble repro'ing this (small caveat see below).  I'm able to get this to work.  `test-config.yaml` has

```yaml
admin:
  endpoint: dns:///flyte.corp.com
  insecure: false
  authType: ClientSecret
  clientId: flytepropeller
  clientSecretLocation: /opt/local/newsecret
  scopes:
    - all
```
where `/opt/local/newsecret` has the password.

The code I'm running is

```python
from flytekit.configuration import PlatformConfig
from flytekit.clients.friendly import SynchronousFlyteClient
cfg = PlatformConfig.auto(config_file="/Users/ytong/test-config.yaml")
client = SynchronousFlyteClient(cfg)
client.list_projects_paginated()
```

The caveat is that the password file cannot have a newline in it.  The current code doesn't strip.  Will add this stripping in a PR for the next release.  cc @eapolinario
