### ISSUE TITLE
[Docs] Document how to set up SSL while using pyflyte run on gcloud cluster

### ISSUE THREAD

**Issue by SmritiSatyanV** [flyteorg/flyte#2893]
### Description

[Slack conversation](https://flyte-org.slack.com/archives/C01P3B761A6/p1663432297323919)
User fixed SSL setup while using pyflyte run after setting up their cluster on gcloud. Used the below steps as mentioned in [google doc](https://docs.google.com/document/d/1skJWmt3hJoIuPQr_RfR-gB9wlatVSIcSD5VlBylJqd8/edit):

Contents of above doc:
1. Follow tutorial upto [SSL cert](https://docs.flyte.org/en/latest/deployment/gcp/manual.html#ssl-certificate)
2. [Install certificate manager](https://cert-manager.io/docs/installation/helm/)
``$ helm repo add jetstack https://charts.jetstack.io``
``$ helm repo update``
``$ kubectl apply -f https://github.com/cert-manager/cert-manager/releases/download/v1.9.1/cert-manager.crds.yaml``
``$ helm install cert-manager jetstack/cert-manager --namespace flyte --create-namespace --version v1.9.1``

3. Add flyte-certificate.yaml
```
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
 name: letsencrypt-production
spec:
 acme:
   server: https://acme-v02.api.letsencrypt.org/directory
   email: <YOUR_EMAIL>
   privateKeySecretRef:
     name: letsencrypt-production
   solvers:
   - selector: {}
     http01:
       ingress:
         class: nginx
```

4. Add the certificate
``$ kubectl apply -f flyte-certificate.yaml``

5. Continue tutorial from [Ingress](https://docs.flyte.org/en/latest/deployment/gcp/manual.html#ingress) to [installing flyte step 3](https://docs.flyte.org/en/latest/deployment/gcp/manual.html#installing-flyte)

6. Modify the values as described, but remove the field for common.ingress.annotations.cert-manager.io/issuer and add
``cert-manager.io/cluster-issuer: "letsencrypt-production"``

7. Continue

### Are you sure this issue hasn't been raised already?

- [X] Yes

### Have you read the Code of Conduct?

- [X] Yes
