### ISSUE TITLE
[BUG] Unexpected node selector merge strategy when using Pod plugin

### ISSUE THREAD

**Issue by cervantes** [flyteorg/flyte#3031]
### Describe the bug

I have a default-node-selector set like so:
```
configmap:
...
  k8s:
    plugins:
      k8s:
...
        default-node-selector:
          algorithm-node: "true"
          "cloud.google.com/gke-smt-disabled": "false"
```

but in my pod task, I add a V1PodSpec with a different node-selector

```
@task(task_config=Pod(pod_spec=V1PodSpec(
        node_selector={
            "large-ssd-node": "true",
            "cloud.google.com/gke-large-ssd": "true",
        },
...)
def mytask():
...
```

However, when I look at the yaml that ultimately gets generated, it seems to be a merge of the two different node-selectors

```
  nodeSelector:
    algorithm-node: "true"
    cloud.google.com/gke-large-ssd: "true"
    cloud.google.com/gke-smt-disabled: "false"
    large-ssd-node: "true"
```

### Expected behavior

Nodeselector from the V1PodSpec should take preference
```
   nodeSelector:
    cloud.google.com/gke-large-ssd: "true"
    large-ssd-node: "true"
```

### Additional context to reproduce

1. Create two node pools:
   * One with labels `algorithm-node: "true"` and `"cloud.google.com/gke-smt-disabled": "false"`
   * One with labels `large-ssd-node: "true"` and `cloud.google.com/gke-large-ssd: "true"`
2. Add the following default-node-selector to k8s plugin
```
        default-node-selector:
          algorithm-node: "true"
          "cloud.google.com/gke-smt-disabled": "false"
```
3. Create a task with the following pod spec, as well as a wrapping workflow, launchplan, etc.
```
@task(task_config=Pod(pod_spec=V1PodSpec(
        node_selector={
            "large-ssd-node": "true",
            "cloud.google.com/gke-large-ssd": "true",
        },
...)
def mytask():
...
```
4. Run that task on the pool.
5. Look at the nodeselector for the scheduled pod.

### Are you sure this issue hasn't been raised already?

- [X] Yes

### Have you read the Code of Conduct?

- [X] Yes
