### ISSUE TITLE
[BUG] Missing GCP field in notifications configuration

### ISSUE THREAD

**Issue by ariefrahmansyah** [flyteorg/flyte#3070]
### Describe the bug

When trying to update to Flyte 1.2.0, `helm diff` command shows `notifications.gcp` field in `flyte-admin-base-config` would be deleted:

```
-       gcp:
-         projectId: gcp-project-id
```

This gcp field got removed on Helm templates in #2781. However, the gcp field seems still needed as shown in [flyteadmin config](https://github.com/flyteorg/flyteadmin/blob/master/pkg/runtime/interfaces/application_configuration.go#L529)

### Expected behavior

The `notifications.gcp` field should not be deleted.

### Additional context to reproduce

In values.yaml, you must set notifications.gcp:

```
workflow_notifications:
  config:
    notifications:
      gcp:
        projectId: gcp-project-id
```

### Are you sure this issue hasn't been raised already?

- [X] Yes

### Have you read the Code of Conduct?

- [X] Yes
