### ISSUE TITLE
[BUG] Lack of defaultBackend for ingress helm chart templates.

### ISSUE THREAD

**Issue by huxuan** [flyteorg/flyte#3077]
### Describe the bug

When deploy to self-hosted kubernetes cluster, it will complains about lack of default backend [1] for the ingress settings.

[1] https://kubernetes.io/docs/concepts/services-networking/ingress/#default-backend

### Expected behavior

Maybe we should have default value with 

```
  defaultBackend:
    service:
      name: flyteconsole
      port:
        number: 80
```

under the spec section?

### Are you sure this issue hasn't been raised already?

- [X] Yes

### Have you read the Code of Conduct?

- [X] Yes
