### ISSUE TITLE
[FlyteCTL Feature] Make default output of `flytectl config init` consistent with the demo sandbox config

### ISSUE THREAD

**Issue by cosmicBboy** [flyteorg/flyte#3186]
### Describe the feature/command for FlyteCTL

Currently, the output of `flytectl config init` is:

```
admin:
  # For GRPC endpoints you might want to use dns:///flyte.myexample.com
  endpoint: dns:///localhost:30081
  authType: Pkce
  insecure: true
logger:
  show-source: true
  level:
```

But the config produced by `flytectl demo start` is:
```
admin:
  # For GRPC endpoints you might want to use dns:///flyte.myexample.com
  endpoint: localhost:30080
  authType: Pkce
  insecure: true
console:
  endpoint: http://localhost:30080
logger:
  show-source: true
  level: 0
```

This may be confusing for new users who would expect the two configs to be consistent

### Provide a possible output or UX example

The output of of `flytectl config init` should be the same as `config-sandbox.yaml`

### Are you sure this issue hasn't been raised already?

- [X] Yes

### Have you read the Code of Conduct?

- [X] Yes

**Comment by Terryhung** [comment]
#take

**Comment by Terryhung** [comment]
## config.yaml
```
admin:
  # For GRPC endpoints you might want to use dns:///flyte.myexample.com
  endpoint: dns:///localhost:30080
  insecure: true
```


## config-sandbox.yaml
```
admin:
  # For GRPC endpoints you might want to use dns:///flyte.myexample.com
  endpoint: localhost:30080
  insecure: true
# This is not a needed configuration, only useful if you want to explore the data in sandbox. For non sandbox, please
# do not use this configuration, instead prefer to use aws, gcs, azure sessions. Flytekit, should use fsspec to
# auto select the right backend to pull data as long as the sessions are configured. For Sandbox, this is special, as
# minio is s3 compatible and we ship with minio in sandbox.
storage:
  connection:
    endpoint: http://localhost:30002
    access-key: minio
    secret-key: miniostorage
```
