### ISSUE TITLE
[BUG] Helm chart handles workflow_notifications region incorrectly

### ISSUE THREAD

**Issue by andrusha** [flyteorg/flyte#3296]
### Describe the bug

Applying helm chart with `workflow_notifications` enabled produces broken configmap yaml for the `region` parameter, thus admin and scheduler fails service deployment.

Eg:
```﻿
﻿notifications.yaml:
----
notifications:
  type: aws
  region:us-east-1
  publisher:
```

Notice `region:us-east-1` misses space after semicolon.

### Expected behavior

Valid yaml should be produced by the helm chart.

**Workaround** add space in your region template values like so: `region: " {{ .Values.userSettings.accountRegion }}"`

### Additional context to reproduce

1. Create `test-values.yaml`
```yaml
userSettings:
  accountRegion: us-east-1
  accountNumber: 123123123
  notifications:
    topicName: topic-name
    queueName: queue-name

workflow_notifications:
  enabled: true
  config:
    notifications:
      type: "aws"
      region: "{{ .Values.userSettings.accountRegion }}"
      publisher:
        topicName: "arn:aws:sns:{{ .Values.userSettings.accountRegion }}:{{ .Values.userSettings.accountNumber }}:{{ .Values.userSettings.notifications.topicName }}"
      processor:
        queueName: "{{ .Values.userSettings.notifications.queueName }}"
        accountId: "{{ .Values.userSettings.accountNumber }}"
      emailer:
        subject: "Flyte: {{ project }}/{{ domain }}/{{ launch_plan.name }} has '{{ phase }}'"
        sender: "{{ .Values.userSettings.notifications.sender }}"
        body: |
          "Execution {{ workflow.project }}/{{ workflow.domain }}/{{ workflow.name }}/{{ name }} has {{ phase }}.
           Details: [https://flyte.example.com/console/projects/{{](https://flyte.example.com/console/projects/%7B%7B) project }}/domains/{{ domain }}/executions/{{ name }}.
           {{ error }}"
```
2. Run `helm template admin flyteorg/flyte-core --version v1.2.1 --values test-values.yaml | grep -A 4 "notifications.yaml"`
3. See:
```yaml
  notifications.yaml: |
    notifications:
      type: aws
      region:us-east-1
      publisher:
```

Which misses space after semicolon.

### Are you sure this issue hasn't been raised already?

- [X] Yes

### Have you read the Code of Conduct?

- [X] Yes
