### ISSUE TITLE
[BUG] flytekit should support the flytectl config.yaml "admin.clientSecretEnvVar" option

### ISSUE THREAD

**Issue by cosmicBboy** [flyteorg/flyte#3482]
### Describe the bug

For context, `pyflyte run` and `pyflyte register` use the flytectl config.yaml file for various configuration settings, including client credential secret. The purpose of this issue is to support the `clientSecretEnvVar` key, which reads the credential from the specified environment variable.

```
admin:
  endpoint: dns:///<your-org.hosted.unionai.cloud>
  clientId: <client-id-from-app-creation>
  # If the secret will be mounted as a file:
  clientSecretLocation: /home/.../<ci-secret>
  # Or, if the secret will be mounted as an environment variable
  clientSecretEnvVar: <env-var>
logger:
  # Logger settings to control logger output. Useful to debug logger:
  show-source: true
  level: 1
```

Currently, flytekit supports the `clientSecretLocation` key, but not the `clientSecretEnvVar`: https://github.com/flyteorg/flytekit/blob/master/flytekit/configuration/__init__.py#L401-L411

### Steps:

- Support reading `admin.clientSecretEnvVar` into the platform config
- If `clientSecretLocation` or `clientSecretEnvVar` is set, automatically set `auth_mode` to `clientSecret` (this is so we match the UnionCloud behavior, see [here](https://app.gitbook.com/o/kvmkVGa8pnIJ0MNPVpTW/s/1qS7FIcEh24liQcmZ6Ib/guides/continuous-integration-ci#setting-up-the-config-file-with-secret-path-and-cluster-endpoint))
- 

### Expected behavior

client-secret-based authentication should work with `admin.clientSecretEnvVar` in the flytectl config.yaml

### Are you sure this issue hasn't been raised already?

- [X] Yes

### Have you read the Code of Conduct?

- [X] Yes
