### ISSUE TITLE
[BUG] - Flytekit - Auth for locally defined scopes

### ISSUE THREAD

**Issue by franco-bocci** [flyteorg/flyte#3486]
### Describe the bug

Locally defined scopes are ignored and others are used which depend on the `authType`.

[This](https://github.com/flyteorg/flytekit/pull/1458/files#diff-68068a13c159b1b1618b3fb6587cbec5fe18f4637414359b8f7580e03e19b536R22) is the remote client config being used which is called [here](https://github.com/flyteorg/flytekit/pull/1458/files#diff-68068a13c159b1b1618b3fb6587cbec5fe18f4637414359b8f7580e03e19b536R95) (and maybe in some other places)
When [this](https://github.com/flyteorg/flytekit/pull/1458/files#diff-68068a13c159b1b1618b3fb6587cbec5fe18f4637414359b8f7580e03e19b536R47) function is called, it receives 2 configs. The one we define (the PlatformConfig), and that RemoteStoreConfig I just linked. scopes passed from the PlatformConfig are 100% ignored, and the ones defined in that RemoteClientConfigStore.get_client_config are used, which are [offline, all]

### Expected behavior

The scopes used for auth should be the ones defined locally.

### Additional context to reproduce

```yaml
admin:
  endpoint: dns:///console.flyte.dev.foo.bar.com
  insecure: false
  authType: ClientSecret
  clientId: github-client
  clientSecretLocation: /etc/secrets/client_secret
  scopes: ["all"]
```

```python
from flytekit.configuration import Config
from flytekit.remote import FlyteRemote


def get_latest_workflow_version(project, domain, workflow):
    cfg = Config.auto(config_file=path)
    remote = FlyteRemote(cfg)
    wf_version = remote.fetch_workflow(project, domain, workflow).id.version
    return wf_version
```

That will use `['offline', 'all']` as the auth scopes, and not `all` as expected.

### Are you sure this issue hasn't been raised already?

- [X] Yes

### Have you read the Code of Conduct?

- [X] Yes
