### ISSUE TITLE
[Docs] Logging links `messageFormat` makes flytepropeller fail

### ISSUE THREAD

**Issue by fg91** [flyteorg/flyte#3664]
### Description

From the [docs explaining how to configure logging](https://docs.flyte.org/projects/cookbook/en/latest/auto/deployment/configure_logging_links.html#how-to-configure):

```
task_logs:
  plugins:
    logs:
      templates:
        - displayName: <name-to-show>
          templateUris:
            - ...
          messageFormat: "json" # "unknown" | "csv" | "json"
```

However, if one sets a `messageFormat`, `flytepropeller` crashes with this error message:

```
Use "flyte-propeller [command] --help" for more information about a command.

time="2023-05-10T13:44:33Z" level=error msg="\n\n\n1 error(s) decoding:\n\n* cannot parse 'templates[0].messageFormat' as int: strconv.ParseInt: parsing \"json\": invalid syntax"
```

Without `messageFormat` everything works.

### Are you sure this issue hasn't been raised already?

- [X] Yes

### Have you read the Code of Conduct?

- [X] Yes
