### ISSUE TITLE
[BUG] Duplicated env vars for pod

### ISSUE THREAD

**Issue by honnix** [flyteorg/flyte#3740]
### Describe the bug

Flyte release 1.6.1.

flytepropeller launched pods have duplicated env vars, for example:
```yaml
   env:
    - name: FLYTE_INTERNAL_EXECUTION_WORKFLOW
      value: ...
    - name: FLYTE_INTERNAL_EXECUTION_ID
      value: ...
    - name: FLYTE_INTERNAL_EXECUTION_PROJECT
      value: ...
    - name: FLYTE_INTERNAL_EXECUTION_DOMAIN
      value: ...
    - name: FLYTE_ATTEMPT_NUMBER
      value: ...
    - name: FLYTE_INTERNAL_TASK_PROJECT
      value: ...
    - name: FLYTE_INTERNAL_TASK_DOMAIN
      value: ...
    - name: FLYTE_INTERNAL_TASK_NAME
      value: ...
    - name: FLYTE_INTERNAL_TASK_VERSION
      value: ...
    - name: FLYTE_INTERNAL_PROJECT
      value: ...
    - name: FLYTE_INTERNAL_DOMAIN
      value: ...
    - name: FLYTE_INTERNAL_NAME
      value: ...
    - name: FLYTE_INTERNAL_VERSION
      value: ...
    - name: FLYTE_PLATFORM_CLOUD_PROVIDER
      value: gcp
    # duplicates start from here
    - name: FLYTE_INTERNAL_EXECUTION_WORKFLOW
      value: ...
    - name: FLYTE_INTERNAL_EXECUTION_ID
      value: ...
    - name: FLYTE_INTERNAL_EXECUTION_PROJECT
      value: ...
    - name: FLYTE_INTERNAL_EXECUTION_DOMAIN
      value: ...
    - name: FLYTE_ATTEMPT_NUMBER
      value: ...
    - name: FLYTE_INTERNAL_TASK_PROJECT
      value: ...
    - name: FLYTE_INTERNAL_TASK_DOMAIN
      value: ...
    - name: FLYTE_INTERNAL_TASK_NAME
      value: ...
    - name: FLYTE_INTERNAL_TASK_VERSION
      value: ...
    - name: FLYTE_INTERNAL_PROJECT
      value: ...
    - name: FLYTE_INTERNAL_DOMAIN
      value: ...
    - name: FLYTE_INTERNAL_NAME
      value: ...
    - name: FLYTE_INTERNAL_VERSION
      value: ...
    - name: FLYTE_PLATFORM_CLOUD_PROVIDER
      value: gcp
```

It seems the same set of env vars are attached twice.

### Expected behavior

No duplicates of env vars.

### Additional context to reproduce

Run any container based task and example the pod.

### Are you sure this issue hasn't been raised already?

- [X] Yes

### Have you read the Code of Conduct?

- [X] Yes
