### ISSUE TITLE
[FlyteCTL Feature] Allow seed project description to be set

### ISSUE THREAD

**Issue by rupurt** [flyteorg/flyte#3742]
### Describe the feature/command for FlyteCTL

Currently you can only set the name of the seed project as a string

https://github.com/flyteorg/flyte/blob/14171fd84d171a609e619a214fa36695fc79990b/cmd/single/config.go#L27
https://github.com/flyteorg/flyte/issues/2503

### Provide a possible output or UX example

Support the current implementation + the ability to set a description

### With Description

```yaml
flyte:
  admin:
    seedProjects:
      - name: myproject
        description: My project description
```

### Without Description

```yaml
flyte:
  admin:
    seedProjects:
      - koi
```

### Are you sure this issue hasn't been raised already?

- [X] Yes

### Have you read the Code of Conduct?

- [X] Yes
