### ISSUE TITLE
[BUG] (flyte-binary) PodTemplates not being read unless a default PodTemplate is configured

### ISSUE THREAD

**Issue by michaeltinsley** [flyteorg/flyte#3946]
### Describe the bug

Flyte Community discussion -> https://flyte-org.slack.com/archives/C01P3B761A6/p1691722283627549?thread_ts=1691585589.382299&cid=C01P3B761A6

Runtime PodTemplates are not being read by Propeller by default, so any request to use a template fails as the template cannot be found, despite the default Cluster Role + SA having the correct permissions.

However, if the `default-pod-template` is configured, Propeller will then read all the available templates and they then work, so it looks like the process to read PodTemplates isn't being started by default.

This behaviour is displaying on Flyte binary v1.8.1.

### Expected behavior

PodTemplates should be read by Propeller by default, even without a default PodTemplate being configured.

### Additional context to reproduce

- Deploy the flyte-binary Helm chart.
- Deploy a PodTemplate.... from the docs:
```
apiVersion: v1
kind: PodTemplate
metadata:
  name: flyte-template-test
  namespace: flyte
template:
  spec:
    containers:
      - name: default
        image: docker.io/rwgrim/docker-noop
        terminationMessagePath: "/dev/foo"
    hostNetwork: false
```
- Deploy a workflow using the template
```
from flytekit import task, workflow

@task(pod_template_name="flyte-template-test")
def check() -> bool:
    return True

@workflow
def run() -> None:
	check()
```

- The task fails

### Are you sure this issue hasn't been raised already?

- [X] Yes

### Have you read the Code of Conduct?

- [X] Yes
