### ISSUE TITLE
[Housekeeping] Make Ingress configuration more generic in `flyte-core`

### ISSUE THREAD

**Issue by davidmirror-ops** [flyteorg/flyte#3968]
### Describe the issue

When `flyte-core` is deployed, several resources exhibit a behavior that could affect the ability to troubleshoot effectively:

1. With `albSSLRedirect: true` it adds an Ingress rule that points to a non-existent service:
```
spec:
  rules:
  - host: flyte-the-hard-way.uniondemo.run
    http:
      paths:
      - backend:
          service:
            name: ssl-redirect
            port:
              name: use-annotation
        path: /*
        pathType: ImplementationSpecific
```

Then, a `kubectl describe` on the deployed Ingress shows an error:

```
Rules:
  Host                              Path  Backends
  ----                              ----  --------
  flyte-the-hard-way.uniondemo.run
                                    /*               ssl-redirect:use-annotation (<error: endpoints "ssl-redirect" not found>)
...
```

Was the idea to use the port from this annotation?:

`alb.ingress.kubernetes.io/ssl-redirect: "443"`

2. The base `values.yaml` file includes hardcoded annotations for the nginx Ingress controller:
 ```
annotations:
      nginx.ingress.kubernetes.io/app-root: /console
```
Even when using another controller, the annotations end up being applied to the deployed resource which could be confusing.

### What if we do not do this?

It affects the User Experience and potentially causes unnecessary distraction during a troubleshooting process.

### Are you sure this issue hasn't been raised already?

- [X] Yes

### Have you read the Code of Conduct?

- [X] Yes
