### ISSUE TITLE
[Core feature] Allow for multiple ingress hosts in helm charts

### ISSUE THREAD

**Issue by LukasBommes** [flyteorg/flyte#3998]
### Motivation: Why do you think this is important?

I need to configure access to our Flyte deployment both from an internal URL (e.g. my-url1.lan) and an external URL (e.g. my-url2.com).

Currently, only one host can be configured in the ingress field of the flyte-core and flyte-binary helm charts. I would need a mechanism to supply two different host names to the ingress resources. 

### Goal: What should the final outcome look like, ideally?

This is supported out-of-the-box by Kubernetes with the following pattern: 

```
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-demo
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
    kubernetes.io/ingress.class: "nginx" 
spec:
  rules:
  - host: my-url1.lan
    http:
      paths:
      - ...
  - host: my-url2.com
    http:
      paths:
      - ...
```
where both "paths" sections contain the same paths as specified in the helm chart (https://github.com/flyteorg/flyte/blob/master/charts/flyte-binary/templates/ingress/http.yaml#L37C8-L37C8).

### Describe alternatives you've considered 

Forwarding from my-url2.com to my-url1.lan does not work in our case.

### Are you sure this issue hasn't been raised already?

- [X] Yes

### Have you read the Code of Conduct?

- [X] Yes
