### ISSUE TITLE
[BUG]  AWS Batch Job’s cpu/mem not following Resources in the task decorator 

### ISSUE THREAD

**Issue by jw0515** [flyteorg/flyte#4003]
### Describe the bug

After bumping flyte from v1.5.0 to v1.6.0 (also the same for v1.9.0, but 1.6.0 is the starting point that having this issue) I found that the task resource config doesn’t propagate to AWS Batch Job’s resource config, I define CPU and memory like this:

`@task(requests=Resources(mem="16Gi", cpu="8"), task_config=AWSBatchConfig(platformCapabilities="EC2"))`

But in AWS batch it’s always the default value that I defined in the helm chart:
```
  task_resource_defaults:
    task_resources:
      defaults:
        cpu: 1000m
        memory: 1000Mi
        storage: 1000Mi
      limits:
        cpu: 256
        memory: 512Gi
        storage: 512Gi
```

### Expected behavior

AWS batch job using the resources I defined in the task decorator. 

### Are you sure this issue hasn't been raised already?

- [X] Yes

### Have you read the Code of Conduct?

- [X] Yes
