### ISSUE TITLE
[BUG] Flyte-Binary Helm chart email notifications don't behave as expected

### ISSUE THREAD

**Issue by peterklingelhofer** [flyteorg/flyte#4024]
### Describe the bug

Myself and another user both seem to be running into an issue with template literals when attempting to add `notifications` inline in the `flyte-binary` helm chart (going off of the [Workflow Notifications](https://docs.flyte.org/en/latest/deployment/configuration/notifications.html#setting-up-workflow-notifications) section in the docs. Here's the Slack thread which details what's occurring: https://discuss.flyte.org/t/14164511/hi-we-are-trying-to-implement-workflow-slack-notifications-w

We see this error when attempting to use `workflow` in a template literal (the same is true of `name`):
`parse error at (flyte-binary/templates/deployment.yaml:4): function "workflow" not defined`. Interestingly, when we don't use template literals, we can build the helm chart successfully and receive notifications, _but_ they come back with this subject: `flyteidl.admin.EmailNotification` (not using the subject we've inputted), and with the body combining these values all into a base64-encoded string: `"<mailto:email@address.com|email@address.com>"email@address.comhi this is the email subject"hi this is the email body`.

Unfortunately, we don't need the extra infrastructure of `flyte-core`, so we were hoping to get this working with the `flyte-binary` chart. In the meantime, I would be very appreciative if anyone has an example of a helm chart for Flyte Binary that has successfully gotten notifications working with the template literals from the example in the docs. Perhaps if there is no immediately obvious solution we can hope the webhooks PR is merged soon: https://github.com/flyteorg/flyteadmin/pull/583

### Expected behavior

Expect the helm chart to build with template literals successfully, so we can see which workflows are failing.

### Additional context to reproduce

```yaml
configuration:
  inline:
    notifications:
      type: "aws"
      region: "us-east-1"
      publisher:
        topicName: "arn:aws:sns:us-east-1:#########:some-name"
      processor:
        queueName: "some-name"
        accountId: "#########"
      emailer:
        sender: "email@address.com"
        subject: "hi this is the email subject"
        body: "hi this is the email body"
```

Yields this in the inline yaml:
```yaml
configuration:
  inline:
    notifications:
      type: "aws"
      region: "us-east-1"
      publisher:
        topicName: "arn:aws:sns:us-east-1:#########:some-name"
      processor:
        queueName: "some-name"
        accountId: "#########"
      emailer:
        sender: "<mailto:email@address.com|email@address.com>"
        subject: "hi this is the email subject"
        body: "hi this is the email body"
```

### Are you sure this issue hasn't been raised already?

- [X] Yes

### Have you read the Code of Conduct?

- [X] Yes
