### ISSUE TITLE
[Docs] Ray plugin setup guide lacks ClusterRole step

### ISSUE THREAD

**Issue by davidmirror-ops** [flyteorg/flyte#4093]
### Description

To make Ray operator work, the ClusterRole that is bound to the Service Account, will need explicit permissions. Otherwise, every attempt to create Ray jobs will fail with the following message:

`W0927 21:10:52.037628       7 reflector.go:324] pkg/mod/k8s.io/client-go@v0.24.1/tools/cache/reflector.go:167: failed to list *v1alpha1.RayJob: rayjobs.ray.io is forbidden: User "system:serviceaccount:flyte:flyte-binary" cannot list resource "rayjobs" in API group "ray.io" at the cluster scope`

The following steps have to be completed for the Ray integration to work on a `flyte-binary` deployment:

1. Add to the `values` file:
```
 rbac:
  extraRules:
    - apiGroups:
    - "ray.io"
    resources:
    - rayjob
    verbs:
    - create
    - get
    - list
    - patch
    - update
```
2. Run a `helm upgrade ...` on the installed release
3. Verify that the changes landed on the ClusterRole

These steps are missing in the setup guide: https://docs.flyte.org/en/latest/deployment/plugins/k8s/index.html

### Are you sure this issue hasn't been raised already?

- [X] Yes

### Have you read the Code of Conduct?

- [X] Yes
