### ISSUE TITLE
[Docs] Change order of cluster resources config example

### ISSUE THREAD

**Issue by neverett** [flyteorg/flyte#4372]
### Description

The copy-pastable config in the [Cluster Resources section](https://docs.flyte.org/en/latest/deployment/configuration/general.html#cluster-resources) of the [Configuring Custom K8s Resources doc](https://docs.flyte.org/en/latest/deployment/configuration/general.htm) cause an error when `uctl update cluster-resource-attribute --attrFile cra.yaml` is run. Changing the ordering in the example to the following will enable it to work with either `uctl` or `flytectl`:

```
domain: development
project: flyteexamples
attributes:
    projectQuotaCpu: "1000"
    projectQuotaMemory: 5Ti
```

### Are you sure this issue hasn't been raised already?

- [X] Yes

### Have you read the Code of Conduct?

- [X] Yes
