### ISSUE TITLE
[Docs] document the process of setting ttl for a ray cluster

### ISSUE THREAD

**Issue by samhita-alla** [flyteorg/flyte#4491]
### Description

ttl for ray cluster can be set in the propeller configmap:

```yaml
k8s.yaml: |
  plugins:
    ray:
      ttlSecondsAfterFinished: 30
```

document the same in the [ray plugin deployment guide](https://docs.flyte.org/en/latest/deployment/plugins/k8s/index.html).

### Are you sure this issue hasn't been raised already?

- [X] Yes

### Have you read the Code of Conduct?

- [X] Yes
