### ISSUE TITLE
[Docs] document the process of adding raw output prefix using flytectl

### ISSUE THREAD

**Issue by samhita-alla** [flyteorg/flyte#4615]
### Description

the raw output data config can be updated using the `flytectl update workflow-execution-config` command.

```yaml
domain: development
project: flytesnacks
raw_output_data_config:
  output_location_prefix: s3://example-data
```

document the same on https://docs.flyte.org/projects/flytectl/en/latest/gen/flytectl_update_workflow-execution-config.html page.

### Are you sure this issue hasn't been raised already?

- [X] Yes

### Have you read the Code of Conduct?

- [X] Yes
