### ISSUE TITLE
[BUG] snowflake plugin causes flyte to not start

### ISSUE THREAD

**Issue by olyashok** [flyteorg/flyte#4721]
### Describe the bug

this guide: https://docs.flyte.org/en/latest/deployment/plugins/webapi/snowflake.html#deployment-plugin-setup-webapi-snowflake
produces
ERROR 2024/01/11 18:38:06 Could not cast sv to map[string]interface{}; key=%!s(MISSING), st=%!v(MISSING), tt=%!v(MISSING), sv=%!v(MISSING), tv=%!v(MISSING) default-for-task-types=[]interface {} map[string]interface {}=[map[container:container] map[container_array:K8S-ARRAY] map[snowflake:snowflake]] map[container:container container_array:k8s-array sidecar:sidecar]=<nil

### Expected behavior

snowflake starts

also this section should have no "-" in docs
![image](https://github.com/flyteorg/flyte/assets/50547198/76066c96-87ff-4586-80f4-b3562d365d80)

### Are you sure this issue hasn't been raised already?

- [X] Yes

### Have you read the Code of Conduct?

- [X] Yes

**Comment by Future-Outlier** [comment]
This works for me.
```yaml
tasks:
  task-plugins:
    enabled-plugins:
      - container
      - sidecar
      - K8S-ARRAY
      - snowflake


    default-for-task-types:
      container: container
      container_array: K8S-ARRAY
      snowflake: snowflake
```
