### ISSUE TITLE
[BUG] Flyte console refreshes often to re-authenticate

### ISSUE THREAD

**Issue by ALMerrill** [flyteorg/flyte#4817]
### Describe the bug

When using the flyte console throughout the day, the console will often refresh and force me to log back in, several times per day. It seems like if I lose focus on the console page for more than 10-20 minutes, when I regain focus on that page, it refreshes. This seems excessive, and it sounds like there should be a way to have it refresh the auth token in the background.

Talking to @davidmirror-ops, I think this is the relevant section of my values file. 

```
    auth:
      appAuth:
        thirdPartyConfig:
          flyteClient:
            clientId: flytectl
            redirectUri: http://localhost:53593/callback
            scopes:
              - offline
              - all
        selfAuthServer:
          staticClients:
            flyte-cli:
              id: flyte-cli
              redirect_uris:
              - http://localhost:53593/callback
              - http://localhost:12345/callback
              grant_types:
                - refresh_token
                - authorization_code
              response_types:
                - code
                - token
              scopes:
                - all
                - offline
                - access_token
              public: true
            flytectl:
              id: flytectl
              redirect_uris:
                - http://localhost:53593/callback
                - http://localhost:12345/callback
              grant_types:
                - refresh_token
                - authorization_code
              response_types:
                - code
                - token
              scopes:
                - all
                - offline
                - access_token
              public: true
            flytepropeller:
              id: flytepropeller
              client_secret: "${secret}"
              redirect_uris:
                - http://localhost:3846/callback
              grant_types:
                - refresh_token
                - client_credentials
              response_types:
                - token
              scopes:
                - all
                - offline
                - access_token
              public: false
```

### Expected behavior

Ideally the token would refresh in the background logins would not be necessary after the initial login

### Additional context to reproduce

This is hosted in GCP, using Google Identity for authentication

### Are you sure this issue hasn't been raised already?

- [X] Yes

### Have you read the Code of Conduct?

- [X] Yes

**Comment by davidmirror-ops** [comment]
@ALMerrill what version of flyte are you running?

**Comment by ALMerrill** [comment]
> @ALMerrill what version of flyte are you running?

1.10.2

**Comment by fg91** [comment]
Our users reported "constantly having to log in" in the flyteconsole (UI) as well. (Using Google IdP and Flyte 1.12)

> Talking to @davidmirror-ops, I think this is the relevant section of my values file.

According to our findings, this is not related to the config in the helm values file above as this only configures Flyte's own auth server which is used for the client credentials flow by the clients in flytekit/flyteidl.

Increasing the lifetime of the access token in this section has no effect on how often users have to login in the UI:

```yaml
appAuth:
    selfAuthServer:
        accessTokenLifespan: 30m0s  <- no effect on UI
```

Instead, we find that when logging in, flyteadmin responds with a `set-cookie` header with a value `flyte_idt` (defined [here](https://github.com/flyteorg/flyte/blob/3f4c2c88748a9fe860bc41788902aef80e83bbc3/flyteadmin/auth/cookie.go#L27)). The token in the cookie is hashed but by setting a breakpoint in flyteadmin [here](https://github.com/flyteorg/flyte/blob/3f4c2c88748a9fe860bc41788902aef80e83bbc3/flyteadmin/auth/cookie.go#L61), we find that the original token expires after 1h. Leaving a tab open after having signed in requires a re-login after exactly 1h which seems to confirm this.

There appears to be no token refresh mechanism in flyteconsole. Other web apps usually refresh the token in the background. Once the token inside the `flyte_idt` cookie expires, requests to the backend result in a 401 and the frontend shows a `Back to Sign in` button. When this is clicked another auth flow is triggered. As the user is stilled logged in to Google, the redirect is almost instant, without seeing a login screen.

Given this, it appears the problem could be avoided by automatically/periodically refreshing the token in the background or by not requiring to press a button and just automatically redirecting to the sign in page - which the user would then never notice. If we are not mistaken, this pop up requiring a button press was only introduced with a recent upgrade of the UI.
