### ISSUE TITLE
[Core feature] Allow namespaces to be used in task templates

### ISSUE THREAD

**Issue by neilisaur** [flyteorg/flyte#4883]
### Motivation: Why do you think this is important?

Currently raw data storage only allows the propeller to provide a single default root S3 location for storing raw data outputs and checkpoints, where normal input/output/error.pb files are stored in a by-namespace key structure.

### Goal: What should the final outcome look like, ideally?

A setting like the following would be a valid storage location that is templated into pod command creations for k8s:
```
    configmap:
      core:
        propeller:
          rawoutput-prefix: "s3://flyte-storage/{{ .Namespace }}"
```

### Describe alternatives you've considered 

Asking all users to specify their `--raw-output-data-prefix` to include the full path to their portion of the bucket that includes their namespace.

### Are you sure this issue hasn't been raised already?

- [X] Yes

### Have you read the Code of Conduct?

- [X] Yes
