### ISSUE TITLE
[BUG] 

### ISSUE THREAD

**Issue by arvind-chandra** [flyteorg/flyte#4926]
### Describe the bug

Add ability to specify labels for Ray Jobs thru the configuration.

### Expected behavior

Add the ability to specify labels to Ray Jobs through configuration. This is needed so that we can filter on certain jobs that are run through Flyte.  

### Are you sure this issue hasn't been raised already?

- [X] Yes

### Have you read the Code of Conduct?

- [X] Yes

**Comment by eapolinario** [comment]
@arvind-chandra , adding labels can be achieved via [pod templates](https://docs.flyte.org/en/latest/deployment/configuration/general.html#deployment-configuration-general).

**Comment by arvind-chandra** [comment]
Hey @eapolinario, the reasoning we had for adding the labels to the Job Spec as opposed to using the pods is because Ray Jobs could have multiple pods. In order to pull from pods, we would have to make extra calls to check for the correct pod before being able to pull from it. On the other hand Ray Jobs always have one RayJob object, so we could directly pull from that without having to go thru the list of pods to get the label.

**Comment by peterghaddad** [comment]
@eapolinario any updates on this one? Can we move it forward?

**Comment by eapolinario** [comment]
@arvind-chandra , @peterghaddad , can you talk a bit more about how adding this fixed value to the propeller config is any better than establishing a convention using pod templates? For example, we could make it so that labels added to the primary container are the ones passed down to the Ray Job.

**Comment by peterghaddad** [comment]
@eapolinario in our particular use case, these labels would be added to every Ray Job so that we can filter Ray Jobs created by Flyte.  Technically we could add a label to all Ray Jobs created by Flyte statically i.e `created/by=flyte` that may also be sufficient, but typically it's better practice to make labels configurable.

In regards to podTemplates, would the user have to define this for each task? If so, then it may be too much overhead.

Let me know your thoughts!

**Comment by peterghaddad** [comment]
@eapolinario Hope you are well! Wanted to follow up here.

**Comment by eapolinario** [comment]
@peterghaddad , forgive me for the delay, we've been busy making sure the next release is up to standards. 

In regards to my suggestion, I should have been more clear. Pod templates [come](https://docs.flyte.org/en/latest/deployment/configuration/general.html#configuring-task-pods-with-k8s-podtemplates) in 2 flavors:
1. compile-time pod templates
2. runtime pod templates

You're probably familiar with 1. as that essentially lets you define a pod template inline as part of defining a task. As you already pointed out, if you had to define that in each and every task then this would be a no-go. However, with runtime pod templates you have a mechanism to set default labels (and annotations) all pods spawned by Flyte. Flytepropeller's config file allows you to set default labels and annotations. In the config file/configmap, under the `k8s` section you can set these values, e.g.:
```
# example config
plugins:
   k8s:
    default-labels:
      label1: label-value1
    default-annotations:
      annotation1: annotation-value1
```

One limitation of this approach is that these labels are going to show up in all pods. You can also use the types of runtime pod templates to be able to target pods to specific namespaces.

**Comment by peterghaddad** [comment]
@eapolinario I think we need this to live at the RayCRD level not the pod level. Can we please re-open this? This is specific to the KubeRay custom resource definition.

**Comment by eapolinario** [comment]
@peterghaddad , we use the podspec and other metadata to build the Ray CRD [already](https://github.com/flyteorg/flyte/blob/master/flyteplugins/go/tasks/plugins/k8s/ray/ray.go#L132-L192) (if you trace the code you'll notice that we [use](https://github.com/flyteorg/flyte/blob/master/flyteplugins/go/tasks/plugins/k8s/ray/ray.go#L428) the pod spec to build the template passed to the Ray CRD). And Flyte pod templates are a way to configure, amongst other fields, labels and annotations to be set for all pods in a namespace.

Just to be clear, if you create a pod template like:
```
apiVersion: v1
kind: PodTemplate
metadata:
  name: flyte-template
  namespace: flytesnacks-development
template:
  metadata:
    labels:
      label1: value1
    annotations:
      foo: bar
      zoo: zaz  # test
  spec:
    containers:
      - name: bogus-name
        image: bogus:image
```

And set the default pod template in the flytepropeller config:
```
    plugins:
      k8s:
        default-pod-template-name: flyte-template
```

And then restart propeller (so that the config is reloaded), all jobs created on the flytesnacks-development from that time on will have the labels and annotations present in the pod template.

**Comment by peterghaddad** [comment]
Hey @eapolinario appreciate the fast response!

I was skimming through the code and still not seeing the pod label being used to set the labels at the Ray Job CRD level. For example:
```
apiVersion: ray.io/v1
kind: RayJob
metadata:
  name: test
  labels:
    created/by: 'flyte'
```

I think this is what we were hoping for because this will enable us to query all Ray Jobs created by flyte using the k8s golang api client.
