### ISSUE TITLE
[Core feature] Allow k8s plugin to pull env from default configMaps / secrets

### ISSUE THREAD

**Issue by neilisaur** [flyteorg/flyte#4968]
### Motivation: Why do you think this is important?

We are able to specify default environment variables through the k8s plugin, but only those hard-coded into the configuration. Allowing default environment variables to be set via configMap or secret would allow automated systems in our environment to access secrets without embedding them in multiple locations.

### Goal: What should the final outcome look like, ideally?

The k8s plugin should have an option where additional environment variable sources can be provided, like:
```
k8s:
  default-cpus: 100m
  default-env-vars:
    - MY_FOO: "bar"
  default-env-vars-from-configmaps:
    - "config-map-a"
    - "config-map-b"
  default-env-vars-from-secrets:
    - "secret-a"
    - "secret-b"
```

### Describe alternatives you've considered 

Inserting environment variables via mutatingWebhooks is the only other method I could see as a basic option, but then I would need a centralized repo of secret values like vault in order to properly store secrets on a per-namespace basis.

### Are you sure this issue hasn't been raised already?

- [X] Yes

### Have you read the Code of Conduct?

- [X] Yes

**Comment by flixr** [comment]
We would also like to have `default-env-vars-from-secrets`... I don't like passing credentials as env vars, but it is currently the only way.
Right now we e.g. have in our flyte-core values.yaml:
```yaml
  k8s:
    plugins:
      k8s:
        default-cpus: 100m
        default-memory: 200Mi
        default-pod-template-name: "flyte-template"
        default-env-vars:
          - FLYTE_AWS_ENDPOINT: "{{ .Values.userSettings.s3.endpoint }}"
          - FLYTE_AWS_ACCESS_KEY_ID: "{{ .Values.userSettings.s3.access_key_id }}"
          - FLYTE_AWS_SECRET_ACCESS_KEY: "{{ .Values.userSettings.s3.secret_key }}"
```
Which also means the credentials are visible to anyone with access to the pod/container envs... not so nice.
