### ISSUE TITLE
[BUG] Task container terminate with error OOMKilled with exit code 137

### ISSUE THREAD

**Issue by spacepirate0001** [flyteorg/flyte#4975]
### Describe the bug

Using `inline` to override Flyte configuration for `task_resources` is not working as expected. I added the following configuration to extend value.yaml in flyte-binary chart:

```
# inline Specify additional configuration or overrides for Flyte, to be merged with the base configuration
  inline:
   task_resources:
    limits:
      cpu: 2
      memory: 3Gi
      ephemeralStorage: 0
      gpu: 0
    defaults:
      cpu: 2
      memory: 3Gi
      ephemeralStorage: 0
      gpu: 0

```
The added configuration did not yield the expected change on `task_resources` and task containers yaml showed the following in terms of resource settings:

```
      name: a4dlhcql89l2zsndtzcp-n1-0
    resources:
      limits:
        cpu: "1"
        memory: 2Gi
      requests:
        cpu: "1"
        memory: 2Gi
```

### Expected behavior

task container resources should reflect the new configurations added to values.yaml i.e. 

```
# inline Specify additional configuration or overrides for Flyte, to be merged with the base configuration
  inline:
   task_resources:
    limits:
      cpu: 2
      memory: 3Gi
      ephemeralStorage: 0
      gpu: 0
    defaults:
      cpu: 2
      memory: 3Gi
      ephemeralStorage: 0
      gpu: 0

``` 

should have task container run with the following resources:
      
```
      name: a4dlhcql89l2zsndtzcp-n1-0
    resources:
      limits:
        cpu: "2"
        memory: 3Gi
      requests:
        cpu: "1"
        memory: 3Gi
```
      

### Are you sure this issue hasn't been raised already?

- [X] Yes

### Have you read the Code of Conduct?

- [X] Yes

**Comment by eapolinario** [comment]
@spacepirate0001 , how did you update the values in the task resources?

**Comment by spacepirate0001** [comment]
> @spacepirate0001 , how did you update the values in the task resources?

I first tried to add it to `clusterResourceTemplates` as follows:
```
    013_flyte_task_resource_defaults.yaml: |
      task_resources:
        defaults:
          cpu: 2
          memory: 3Gi
          ephemeralStorage: 0
          gpu: 0
        limits:
          cpu: 2
          memory: 3Gi
          ephemeralStorage: 0
          gpu: 0  
```
It did not work then I added it as `configuration.inline`:

```
#inline Specify additional configuration or overrides for Flyte, to be merged with the base configuration
  inline:  
    task_resources:
      limits:
        cpu: 2
        memory: 3Gi
        ephemeralStorage: 0
        gpu: 0
      defaults:
        cpu: 2
        memory: 3Gi
        ephemeralStorage: 0
        gpu: 0
```
This partially worked as new task_resource run with the following:
```
resources:
      limits:
        cpu: "1"
        memory: 2Gi
      requests:
        cpu: "1"
        memory: 2Gi
```
My tasks need more resources which end up with the error OOMKilled with exit code 137

**Comment by eapolinario** [comment]
@spacepirate0001 , how are you updating the values? Can you share the commands you used? Also, can you confirm which `requests` and `limits` values, if any, you were using in the tasks you tested on?

**Comment by spacepirate0001** [comment]
Code is deployed via terraform module updates and I can see the changes I make being reflected on the manifest. You should try the same in your setup and see that the values don’t change beyond what I’ve mentioned. Finally I’m running flyte-binary chart in which I did not find values for task_resources at all.

**Comment by cjidboon94** [comment]
Also ran into this issue

**Comment by cjidboon94** [comment]
In my `flyte-binary` values I've set as suggested here https://github.com/davidmirror-ops/flyte-the-hard-way/blob/main/docs/aws/05-deploy-with-helm.md#time-for-helm
```yaml
configuration:
  inline: 
    task_resources:
     defaults:
        cpu: 500m
        memory: 500Mi
        storage: 500Mi
      limits:
        cpu: "10"
        memory: 20Gi
 ```

However when I try to register a workflow with tasks that has a task with a limit set to `cpu=4`, I get the following error response:
```
USER:BadInputToAPI: error=None, cause=<_InactiveRpcError of RPC that terminated with:
        status = StatusCode.INVALID_ARGUMENT
        details = "Requested CPU limit [4] is greater than current limit set in the platform configuration [2]. Please contact Flyte Admins to change these limits or consult the configuration"
        debug_error_string = "UNKNOWN:Error received from peer  {grpc_message:"Requested CPU limit [4] is greater than current limit set in the platform configuration [2]. Please contact Flyte Admins to change these limits or consult the configuration", grpc_status:3, created_time:"2024-03-20T11:29:01.232266149+01:00"}"
```
If  I run `flytectl get task-resource-attribute -p flytesnacks -d development`, I get
`{"project":"flytesnacks","domain":"development","defaults":{"cpu":"1","memory":"150Mi"},"limits":{"cpu":"2","memory":"2Gi"}}` as a response, which doesn't seem to match my values but rather the default values.
