### ISSUE TITLE
[BUG]  Environment variables not propagating into copilot

### ISSUE THREAD

**Issue by samuel-sujith** [flyteorg/flyte#5012]
### Describe the bug

I m trying to run the raw container example given here
https://docs.flyte.org/en/latest/user_guide/customizing_dependencies/raw_containers.html

On trying the latest version of copilot, it gives me the below error
{"json":{},"level":"error","msg":"failed to get AWS credentials: NoCredentialProviders: no valid providers in chain. Deprecated.\n\tFor verbose messaging see aws.Config.CredentialsChainVerboseErrors","ts":"2024-03-06T04:41:42Z"}

I understand from this that the copilot initcontainer is trying to get the values from ENV Vars but the started initcontainer doesnt have the env vars for AWS access

I see that in the flyte workflow pod definition, copilot is not getting the env vars.

```
initContainers:
    - name: flyte-copilot-downloader
      image: cr.flyte.org/flyteorg/flytecopilot:v1.11.0-b1
      command:
        - /bin/flyte-copilot
        - '--storage.limits.maxDownloadMBs=0'
        - '--storage.container=india-flytedata'
        - '--storage.type=s3'
        - >-
          --storage.connection.secret-key=temp
        - '--storage.connection.access-key=temp'
        - '--storage.connection.auth-type=accesskey'
        - '--storage.connection.region=us-east-1'
        - '--storage.connection.endpoint=temp'
      args:
        - download
        - '--from-remote'
        - >-
          s3://india-flytedata/metadata/propeller/samuel-rawcontainer-development-agrv92bxkl9qprh6n28z/n1/data/inputs.pb
        - '--to-output-prefix'
        - >-
          s3://india-flytedata/metadata/propeller/samuel-rawcontainer-development-agrv92bxkl9qprh6n28z/n1/data/0
        - '--to-local-dir'
        - /var/inputs
        - '--format'
        - JSON
        - '--input-interface'
        - CgkKAWESBAoCCAIKCQoBYhIECgIIAg==
      workingDir: /
      resources:
        limits:
          cpu: 500m
          memory: 128Mi
        requests:
          cpu: 500m
          memory: 128Mi
      volumeMounts:
        - name: flyte-inputs
          mountPath: /var/inputs
        - name: kube-api-access-s9cmc
          readOnly: true
          mountPath: /var/run/secrets/kubernetes.io/serviceaccount
```

But the container gets the env var

```
containers:
    - name: agrv92bxkl9qprh6n28z-n1-0
      image: ghcr.io/flyteorg/rawcontainers-julia:v2
      command:
        - julia
        - calculate-ellipse-area.jl
        - '3.4'
        - '4.2'
        - /var/outputs
      env:
        - name: FLYTE_INTERNAL_EXECUTION_WORKFLOW
          value: samuel-rawcontainer:development:rawcontainer.my_workflow.wf
        - name: FLYTE_INTERNAL_EXECUTION_ID
          value: agrv92bxkl9qprh6n28z
        - name: FLYTE_INTERNAL_EXECUTION_PROJECT
          value: samuel-rawcontainer
        - name: FLYTE_INTERNAL_EXECUTION_DOMAIN
          value: development
        - name: FLYTE_ATTEMPT_NUMBER
          value: '0'
        - name: FLYTE_INTERNAL_TASK_PROJECT
          value: samuel-rawcontainer
        - name: FLYTE_INTERNAL_TASK_DOMAIN
          value: development
        - name: FLYTE_INTERNAL_TASK_NAME
          value: ellipse-area-metadata-julia
        - name: FLYTE_INTERNAL_TASK_VERSION
          value: 20240305-190734
        - name: FLYTE_INTERNAL_PROJECT
          value: samuel-rawcontainer
        - name: FLYTE_INTERNAL_DOMAIN
          value: development
        - name: FLYTE_INTERNAL_NAME
          value: ellipse-area-metadata-julia
        - name: FLYTE_INTERNAL_VERSION
          value: 20240305-190734
        - name: AWS_SECRET_ACCESS_KEY
          value: temp
        - name: AWS_REGION
          value: us-east-1
        - name: AWS_ENDPOINT
          value: temp
        - name: AWS_S3_US_EAST_1_REGIONAL_ENDPOINT
          value: temp
        - name: FLYTE_AWS_ENDPOINT
          value: temp
        - name: FLYTE_AWS_ACCESS_KEY_ID
          value: temp
        - name: FLYTE_AWS_SECRET_ACCESS_KEY
          value: temp
        - name: AWS_ACCESS_KEY_ID
          value: temp
```

even in the containers, the copilot side car is not getting the env vars

I have specified the correct setting in the copilot k8s plugin

```
  copilot.yaml: |
    plugins:
      k8s:
        FLYTE_AWS_ACCESS_KEY_ID: 11
        FLYTE_AWS_ENDPOINT: temp
        FLYTE_AWS_SECRET_ACCESS_KEY: I11
        default-cpus: 100m
        default-env-vars:
        - FLYTE_AWS_ENDPOINT: 11
        - FLYTE_AWS_ACCESS_KEY_ID: 11
        - FLYTE_AWS_SECRET_ACCESS_KEY:11
        - FLYTE_AWS_ENDPOINT: 11
        - AWS_ACCESS_KEY_ID: 11
        - AWS_SECRET_ACCESS_KEY: 11
        - AWS_REGION: us-east-1
        - AWS_ENDPOINT: 11
        - AWS_S3_US_EAST_1_REGIONAL_ENDPOINT: 11
        co-pilot:
          image: cr.flyte.org/flyteorg/flytecopilot:v1.11.0-b1
          name: flyte-copilot-
          start-timeout: 30s
          storage: 200Mi
```

Please assist

### Expected behavior

ENV vars should propagate into copilot containers and it should download the data from S3

### Are you sure this issue hasn't been raised already?

- [X] Yes

### Have you read the Code of Conduct?

- [X] Yes
