### ISSUE TITLE
Add a securitySchemes to swagger.json

### ISSUE THREAD

**Issue by pingsutw** [flyteorg/flyte#5160]
### Motivation: Why do you think this is important?

Users will be able to test admin APIs that use OAuth2 on [swagger UI](https://petstore.swagger.io/?_gl=1*8rj2nt*_gcl_au*MzQ3MTg0MTY3LjE3MTE4Njg4MjU.&_ga=2.138279480.98378179.1711868825-1021132267.1711868824#/AdminService)

### Goal: What should the final outcome look like, ideally?

Add a securitySchemes to [swagger.json](https://github.com/flyteorg/flyte/blob/master/flyteidl/clients/go/assets/admin.swagger.json)

here is an example

```yaml
# Step 1 - define the security scheme
components:
  securitySchemes:
    oAuthSample:    # <---- arbitrary name
      type: oauth2
      description: This API uses OAuth 2 with the implicit grant flow. [More info](https://api.example.com/docs/auth)
      flows:
        implicit:   # <---- OAuth flow(authorizationCode, implicit, password or clientCredentials)
          authorizationUrl: https://api.example.com/oauth2/authorize
          scopes:
            read_pets: read your pets
            write_pets: modify pets in your account
```
https://swagger.io/docs/specification/authentication/oauth2/Here

### Describe alternatives you've considered 

NA

###  Propose: Link/Inline OR Additional context 

https://swagger.io/docs/specification/authentication/oauth2/

### Are you sure this issue hasn't been raised already?

- [X] Yes

### Have you read the Code of Conduct?

- [X] Yes
