### ISSUE TITLE
[BUG] flyteadmin Liveness probe is often timing out and triggers a pod restart

### ISSUE THREAD

**Issue by rambrus** [flyteorg/flyte#5539]
### Describe the bug

In our PROD environment, `flyteadmin` pod often gets restarted due to Liveness probe timeout:
![image](https://github.com/flyteorg/flyte/assets/10614761/4853160e-e7ee-4af6-b2de-4ca83d5b72bc)

We host Flyte on EKS (v1.25.16-eks-3af4770) and use the default Readiness and Liveness config for `flyteadmin`:
```
       readinessProbe:
          exec:
            command: [ "sh", "-c", "reply=$(curl -s -o /dev/null -w %{http_code} http://127.0.0.1:8088/healthcheck); if [ \"$reply\" -lt 200 -o \"$reply\" -ge 400 ]; then exit 1; fi;","grpc_health_probe", "-addr=:8089"]
          initialDelaySeconds: 15
        livenessProbe:
          exec:
            command: [ "sh", "-c", "reply=$(curl -s -o /dev/null -w %{http_code} http://127.0.0.1:8088/healthcheck); if [ \"$reply\" -lt 200 -o \"$reply\" -ge 400 ]; then exit 1; fi;","grpc_health_probe", "-addr=:8089"]
          initialDelaySeconds: 20
          periodSeconds: 5
```

We suspect that probe hangs while running the grpc_health_probe, as we have also observed that Kubernetes struggles with the pod termination (in some cases, it takes 10-15 minutes to restart the pod).
I have checked the pod resource usage, it seems fine: 
![image](https://github.com/flyteorg/flyte/assets/10614761/1f4cb4c6-f31d-490d-8de1-167f6f04edbe)

We are running Flyte v11.0 with this flyteadmin config:
```
flyteadmin:
  replicaCount: null
  image:
    tag: v1.11.0-0.0.14
  maxParallelism: 25
  resources:
    limits:
      cpu: 250m
      ephemeral-storage: 5Gi
      memory: 500Mi
    requests:
      cpu: 10m
      ephemeral-storage: 5Gi
      memory: 50Mi
  hpa:
    enabled: true
    minReplicas: 4
  vault:
    ...
  affinity:
    podAntiAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        - labelSelector:
            matchLabels:
              app.kubernetes.io/name: ml-platform-flyte-flyteadmin
          topologyKey: kubernetes.io/hostname
```
Any ideas / suggestions are welcome!

### Expected behavior

Liveness probe succeeded

### Are you sure this issue hasn't been raised already?

- [X] Yes

### Have you read the Code of Conduct?

- [X] Yes
