### ISSUE TITLE
[Docs] auth setup page issues

### ISSUE THREAD

**Issue by davidmirror-ops** [flyteorg/flyte#5552]
### Description

We need to fix the following problems for the [auth setup docs](https://docs.flyte.org/en/latest/deployment/configuration/auth_setup.html) to be more precise:

1. The [steps for MS Entra ID](https://docs.flyte.org/en/latest/deployment/configuration/auth_setup.html#identity-management-layer-oidc) have to be updated to reflect the current location of settings on the Azure UI
2. The indentation for `configmap.adminServer.security` is wrong. It should be one level deeper (under `server`):
```
configmap:
  adminServer:
    server:
      httpPort: 8088
      grpc:
        port: 8089
      security:
        secure: false
        useAuth: true
        allowCors: true
        allowedOrigins:
 # Accepting all domains for Sandbox installation
          - "*"
        allowedHeaders:
          - "Content-Type"
```
4. Step 8 and beyond are folded inside the Note block when it should be out
5. There have been users indicating that in general, this page is hard to understand. Try to improve verbiage to make it easier to follow.

### Are you sure this issue hasn't been raised already?

- [X] Yes

### Have you read the Code of Conduct?

- [X] Yes
