### ISSUE TITLE
[Core Feature]: Allow to configure agent status update frequency

### ISSUE THREAD

**Issue by thomas-maschler** [flyteorg/flyte#5733]
I have an asynchronous agent that schedules long-running jobs using a third-party service. That service has request quotas. 
Right now, agents request a status update every 5s. When running many long-running tasks concurrently I frequently run into quota limits and my status updates fail. 

I would like to configure the status update frequency for my agent in a similar way, I can configure timeouts.
https://docs.flyte.org/en/latest/flyte_agents/developing_agents.html#canary-deployment

**Comment by pingsutw** [comment]
You should be able to configure it by updating this [config](https://github.com/flyteorg/flyte/blob/89efcc62a6dfc6f28d679898445cdc5ddb2d964b/flyteplugins/go/tasks/plugins/webapi/agent/config.go#L28)

**Comment by kumare3** [comment]
@thomas-maschler as @pingsutw said, this is already supported in Agents today. please use this to adjust. 
@pingsutw maybe we should make it possible to adjust it from the AgentMetadata service (in the future)?

**Comment by thomas-maschler** [comment]
@pingsutw following up on this thread.

I tried updating our config and used `webApi.caching.resyncInterval` to change the update frequency. That didn't work and my agent still polled every ~10sec.

```yaml
flyteagent:
  enabled: true
  plugin_config:
    plugins:
      agent-service:
        defaultAgent:
          endpoint: "dns:///flyteagent.flyte-core.svc.cluster.local:8000"
          insecure: true
        agents:
          my-custom-agent:
            endpoint: "dns:///my-custom-agent.my-namespace.svc.cluster.local:8000"
            insecure: true
            timeouts:
              CreateTask: 5s
              GetTask: 30s
              DeleteTask: 30s
            defaultTimeout: 30s
            # Only run the agent `get` method once a minute
            webApi:
              caching:
                resyncInterval: 60s
```

I also tried using `pollInterval` without success

```yaml
flyteagent:
  enabled: true
  plugin_config:
    plugins:
      agent-service:
        defaultAgent:
          endpoint: "dns:///flyteagent.flyte-core.svc.cluster.local:8000"
          insecure: true
        agents:
          my-custom-agent:
            endpoint: "dns:///my-custom-agent.my-namespace.svc.cluster.local:8000"
            insecure: true
            timeouts:
              CreateTask: 5s
              GetTask: 30s
              DeleteTask: 30s
            defaultTimeout: 30s
            # Only run the agent `get` method once a minute
            pollInterval: 60s
```

Can you post an example on how to configure the canary agent correctly to poll less frequently?
