### ISSUE TITLE
[Docs] Ray plugin documentation missing details

### ISSUE THREAD

**Issue by davidmirror-ops** [flyteorg/flyte#5738]
### Description

To ensure [the example](https://docs.flyte.org/en/latest/flytesnacks/examples/ray_plugin/index.html) is reproducible, the following elements are missing:

1. Make imports visible in the docs page, not only in the flytesnacks repo
2. How to set up the ClusterRole with the permissions to create `rayjobs`. Otherwise the example throws an error. This could be part of the [plugin setup guide](https://docs.flyte.org/en/latest/deployment/plugins/k8s/index.html#deployment-plugin-setup-k8s)

`cannot create resource "rayjobs" in API group "ray.io" in the namespace "flytesnacks-development`

In particular, the ClusterRole is missing the following permissions:

```
rbac:
  extraRules:
    - apiGroups:
      - "ray.io"
      resources:
      - rayjobs
      verbs:
      - create
      - get
      - list
      - patch
      - update
      - delete
```

### Are you sure this issue hasn't been raised already?

- [X] Yes

### Have you read the Code of Conduct?

- [X] Yes
