### ISSUE TITLE
[Docs] Update logging links documentation for Cloudwatch

### ISSUE THREAD

**Issue by davidmirror-ops** [flyteorg/flyte#5760]
### Description

The current [docs page](https://docs.flyte.org/en/latest/user_guide/productionizing/configuring_logging_links_in_the_ui.html#configure-logging) includes an example that is generic and uses outdated configuration:

```
task_logs:
  plugins:
    logs:
      templates:
        - displayName: <name-to-show>
          templateUris:
            - "https://console.aws.amazon.com/cloudwatch/home?region=us-east-1#logEventViewer:group=/flyte-production/kubernetes;stream=var.log.containers.{{.podName}}_{{.namespace}}_{{.containerName}}-{{.containerId}}.log"
            - "https://some-other-source/home?region=us-east-1#logEventViewer:group=/flyte-production/kubernetes;stream=var.log.containers.{{.podName}}_{{.namespace}}_{{.containerName}}-{{.containerId}}.log"
          messageFormat: 0 # this parameter is optional, but use 0 for "unknown", 1 for "csv", or 2 for "json
```

Considering the notes and fields on the current struct:
https://github.com/flyteorg/flyte/blob/0eaa20e8b92245555be8fd725f97e52fbed54e78/flyteplugins/go/tasks/logs/config.go#L11-L34

The Cloudwatch example should use the supported fields and a baseline`templateUri` structure, indicating the prerequisites for log links to work on EKS ( [Cloudwatch Observability for EKS add-on](https://docs.aws.amazon.com/AmazonCloudWatch/latest/monitoring/Container-Insights-setup-EKS-addon.html)).

Also the base Helm `values` should include the config structure, with logging disabled by default.

---

### Are you sure this issue hasn't been raised already?

- [X] Yes

### Have you read the Code of Conduct?

- [X] Yes

**Comment by oluwatobi2001** [comment]
Hi interested

**Comment by 3kis** [comment]
hi! i'm interested in this issue, can you assign me ?

**Comment by vinayJ74** [comment]
can you assign me this i would love to contribute in this issue

**Comment by davidmirror-ops** [comment]
@vinayJ74 @3kis @oluwatobi2001 thanks for your interest in contributing. Remember that the `hacktoberfest-accepted` label is granted to the first merged PR, regardless if it came from the issue assignee or from someone else. Let us know any questions.

**Comment by graykeng** [comment]
Hi David, do you still need a contributor to this issue? I'm interested in this issue. Thank you.

**Comment by davidmirror-ops** [comment]
Still needed.

Also add the following for the K8s dashboard

```
plugins:
  logs:
    kubernetes-enabled: true
    kubernetes-template-uri: 'http://<YOUR_DASHBOARD_URL>/#/log/{{ "{{" }}.namespace {{ "}}" }}/{{ "{{" }} .podName {{ "}}" }}/pod?namespace={{ "{{" }} .namespace {{ "}}" }}'
```
