### ISSUE TITLE
[BUG]  Tasks get stuck in Queued status

### ISSUE THREAD

**Issue by sorushsaghari** [flyteorg/flyte#5927]
### Describe the bug

Tasks in the Flyte deployment are not executing and remain in either an unknown or queued state indefinitely. No task progresses to the running or completed state, effectively halting workflow execution.

### Expected behavior

Tasks should transition from the queued state to running, followed by completion, provided that no errors or resource constraints are encountered.

### Additional context to reproduce

1- Set up Flyte using the provided Helm configuration.
2- Trigger a workflow that contains at least one task.
3- Observe that the tasks remain in queued status without progressing.

Helm configuration:
```yaml
flyte-core-components:
  admin:
    disabled: false
    disableScheduler: false
    disableClusterResourceManager: false
    seedProjects:
      - <project-name>

  propeller:
    disabled: false
    disableWebhook: false
  dataCatalog:
    disabled: false

deployment:
  image:
    repository: <docker-registry-url>/flyte-binary-release
    tag: v1.13.3
  resources:
    limits:
      memory: 4Gi
      cpu: 3
    requests:
      memory: 4Gi
      cpu: 2
  waitForDB:
     image:
      repository: <docker-registry-url>/postgres

configuration:
  database:
    username: <db-username>
    password: <db-password>
    host: <db-host>
    port: 5432
    dbname: <db-name>
    options: sslmode=disable

  storage:
    metadataContainer: <meta-container>
    userDataContainer: <user-container>
    provider: s3
    providerConfig:
      s3:
        disableSSL: true
        v2Signing: true
        authType: accesskey
        accessKey: <s3-access-key>
        secretKey: <s3-secret-key>
        endpoint: "<s3-endpoint>"

  logging:
    show-source: true
    level: 15

  auth:
    enabled: false
  co-pilot:
    image:
      repository: <docker-registry-url>/flytecopilot
      tag: v1.13.3

service:
  type: ClusterIP

ingress:
  create: true
  host: <flyte-host-url>
  separateGrpcIngress: true

rbac:
  create: true
  extraRules:
    - apiGroups:
        - "ray.io"
      resources:
        - rayclusters
        - rayjobs
        - rayservices
      verbs:
        - "*"

serviceAccount:
  create: true
```
![image](https://github.com/user-attachments/assets/50a14fe6-9549-41c9-8687-7a762902bee6)

### Are you sure this issue hasn't been raised already?

- [X] Yes

### Have you read the Code of Conduct?

- [X] Yes
