### ISSUE TITLE
[BUG] Submit task to specified cluster does not take effect problem

### ISSUE THREAD

**Issue by daadc** [flyteorg/flyte#5966]
### Describe the bug

local use of control cluster configuration, after submitting tasks to the data cluster, the specified data cluster did not create task-related pods, but the control cluster created corresponding pods.

### Expected behavior

submit the task to the specified cluster and create the corresponding pod to run the task

### Additional context to reproduce

# Environment:
- Flyte 1.13.3
- test.py
```python
from flytekit import task, workflow

@task
def a() -> str:
    return 'a'

@task
def b() -> str:
    return 'b'

@workflow
def wf_2() -> str:
    print(a())
    return b()

if __name__ == "__main__":
    print(f"Running training_workflow() {wf_1()}")
``` 
- cluster configuration
```yaml
flyteadmin:
  additionalVolumes:
  - name: cluster-credentials
    secret:
      secretName: cluster-credentials
  additionalVolumeMounts:
  - name: cluster-credentials
    mountPath: /var/run/credentials
  initContainerClusterSyncAdditionalVolumeMounts:
  - name: cluster-credentials
    mountPath: /etc/credentials
configmap:
  clusters:
   labelClusterMap:
    data-cluster1:
     - id: data-cluster1
       weight: 1
   clusterConfigs:
   - name: "data-cluster1"
     endpoint: https://xxxxx
     enabled: true
     auth:
        type: "file_path"
        tokenPath: "/var/run/credentials/data_cluster1_token"
        certPath: "/var/run/credentials/data_cluster1_cacert"
     inCluster: true
```
- Pod for testing connectivity
```
apiVersion: v1
kind: Pod
metadata:
  name: test-sa-pod
spec:
  serviceAccountName: flyteadmin
  containers:
  - name: alpine
    image: curlimages/curl
    command:
      - "sh"
      - "-c"
      - "apk add curl || sleep infinity"
    volumeMounts:
    - mountPath: /var/run/credentials
      name: cluster-secrets
  volumes:
  - name: cluster-secrets
    secret:
      defaultMode: 420
      secretName: cluster-credentials
```
- pod executed command
```bash
 curl -sSk -H "Authorization: Bearer $(cat /var/run/credentials/data_cluster1_token)" https://xxxx:6443/api
/v1/namespaces/flyte-data/pods
```
# Problem reproduce:
```bash
# first cluster label 、project and domain is true
❯ flytectl get execution-cluster-label --project my-project-3 --domain development
{"project":"my-project-3","domain":"development","value":"data-cluster1"}
# submit task
❯ pyflyte run --remote  -p my-project-3 -d development  --ecl data-cluster1 test.py wf_2
Running Execution on Remote.
Promise(node:n0.o0.[])

[✔] Go to http://xxxxxx:30289/console/projects/my-project-3/domains/development/executions/afbdghrcgmmns4l5jjcd to see execution in the console.
```

### Screenshots
![image](https://github.com/user-attachments/assets/9c586685-3410-4bc0-9d6f-bb09ec0bf4b7)
![img_v3_02gc_15db87f6-d732-4a67-a481-d9a79a5a0a8g](https://github.com/user-attachments/assets/62ff6d8a-259c-4c14-bf37-df65c4fc93b3)

### Are you sure this issue hasn't been raised already?

- [X] Yes

### Have you read the Code of Conduct?

- [X] Yes

**Comment by daadc** [comment]
I would like to provide an update regarding the issue I previously reported. It has now been resolved
Today resubmitting the task, I checked the front-end and found an error message saying
```
failed to create workflow in propeller execution cluster label data-cluster1 is not supported...
```

After revisiting the configuration within our cluster, I discovered that the overrides specified in `value-override.yaml` were not properly applied during the helm upgrade process. This oversight resulted in the `configmaps.clusters.configConfigs` settings not being reflected in the cluster as intended.

In my initial check of the configuration, I performed a simple grep search for the cluster label:
```
❯ k get cm -o yaml | grep data-cluster1
          data-cluster1:
          - id: data-cluster1
          data-cluster1:
          - id: data-cluster1
```
Unfortunately, this method was inadequate as I did not thoroughly review the actual contents of the configuration file, which would have revealed the discrepancy.

I sincerely apologize for the oversight and for any disruption this may have caused to the team. The situation has provided valuable learning, particularly the importance of meticulously verifying configuration changes post-deployment.

Thank you for your patience and understanding.
