### ISSUE TITLE
[BUG] ZIP does not support timestamps before 1980

### ISSUE THREAD

**Issue by LemontreeN** [flyteorg/flyte#5994]
### Describe the bug

same with the below page，error : ZIP does not support timestamps before 1980
when execute the spark sample code
https://discuss.flyte.org/t/23214966/hi-everyone-wave-i-m-new-here-and-this-is-my-first-message-i

### Expected behavior

The sample code should execute normally.

### Are you sure this issue hasn't been raised already?

- [X] Yes

### Have you read the Code of Conduct?

- [X] Yes

**Comment by eapolinario** [comment]
@LemontreeN , how are you checking out the flytesnacks repo? Also, can you share other details like OS, python version, and flytekit versions?

**Comment by LemontreeN** [comment]
``` bash
pyflyte run --remote -p p1 -d development spark.py my_spark
```
error same with the discuss,
envs of server and client as follows:
## Server
### Base environments
- Flyte-core (multi-cluster version): v1.13.3
- Spark Operator Controller: 2.0.2
- Kubernetes Server Version: v1.26.3-aliyun.1
### Installation and configuration steps:
 1. https://docs.flyte.org/en/latest/deployment/plugins/k8s/index.html#install-the-kubernetes-operator
 2. edit flyte-controller-plane & data-plane Spark Configuration
enabled spark plugin from the 
https://github.com/flyteorg/flyte/blob/d2ddfe26041c4441139001c289c9c0e10bd3d319/charts/flyte-core/values.yaml#L854 
as follows
``` yaml
configmap:
  enabled_plugins:
    tasks:
      task-plugins:
        enabled-plugins:
          - container
          - sidecar
          - k8s-array
          - agent-service
          - echo
          - spark
        default-for-task-types:
          container: container
          sidecar: sidecar
          container_array: k8s-array
          spark: spark
```
enabled sparkoperator from the [flyte/charts/flyte-core/values.yaml at d2ddfe26041c4441139001c289c9c0e10bd3d319 · flyteorg/flyte](https://github.com/flyteorg/flyte/blob/d2ddfe26041c4441139001c289c9c0e10bd3d319/charts/flyte-core/values.yaml#L1072) as follows
``` yaml
sparkoperator:
  enabled: true
  plugin_config:
    plugins:
      spark:
        spark-config-default:
          - spark.driver.cores: "1"
          Uncomment and set the S3 credentials if required
          - spark.hadoop.fs.s3a.aws.credentials.provider: "org.apache.hadoop.fs.s3a.SimpleAWSCredentialsProvider"
          - spark.hadoop.fs.s3a.endpoint: <S3_ENDPOINT>
          - spark.hadoop.fs.s3a.access.key: "<ACCESS_KEY>"
          - spark.hadoop.fs.s3a.secret.key: "<SECRET_KEY>"
          - spark.hadoop.fs.s3a.path.style.access: "true"
          - spark.kubernetes.allocation.batch.size: "50"
          - spark.hadoop.fs.s3a.acl.default: "BucketOwnerFullControl"
          - spark.hadoop.fs.s3n.impl: "org.apache.hadoop.fs.s3a.S3AFileSystem"
          - spark.hadoop.fs.AbstractFileSystem.s3n.impl: "org.apache.hadoop.fs.s3a.S3A"
          - spark.hadoop.fs.s3.impl: "org.apache.hadoop.fs.s3a.S3AFileSystem"
          - spark.hadoop.fs.AbstractFileSystem.s3.impl: "org.apache.hadoop.fs.s3a.S3A"
          - spark.hadoop.fs.s3a.impl: "org.apache.hadoop.fs.s3a.S3AFileSystem"
          - spark.hadoop.fs.AbstractFileSystem.s3a.impl: "org.apache.hadoop.fs.s3a.S3A"
```
3. configure the resource manager templates according to the 
4. https://docs.flyte.org/en/latest/deployment/plugins/k8s/index.html#specify-plugin-configuration spark.flyte-core.aws.
upgrade the flyte-controller-plane and data-plane
## Client
flytekit 1.13.12
Python 3.10.15
flytekitplugins-spark    1.13.13
OS: Windows 10
