### ISSUE TITLE
[BUG] Flytectl authentication not working with GCP IAP

### ISSUE THREAD

**Issue by gverkes** [flyteorg/flyte#6089]
### Describe the bug

After having set up IAP with Flyte according to https://pypi.org/project/flytekitplugins-identity-aware-proxy/, the `flytectl` command during flyte authentication seems to fail due to IAP. During the Flyte authentication the initial IAP works fine, but during the callback I get the error: `Couldn't get access token due to error: oauth2: cannot fetch token: 401 Unauthorized Response: Invalid IAP credentials: empty token`. Connecting through Flytekit  or the console works fine.

### Expected behavior

The proxyCommand provides a token for IAP, that should be properly propagated, such that the Flyte authentication succeeds. Just like Flytekit

### Additional context to reproduce

1. Setup Flyte + IAP according to the tutorial on https://pypi.org/project/flytekitplugins-identity-aware-proxy/
2. Set `config.yaml` to something like (also used for flytekit, which does work):
```
admin:
  endpoint: dns:///example.com
  insecure: false
  insecureSkipVerify: false
  authType: Pkce
  proxyCommand: ["flyte-iap", "generate-user-id-token", "--desktop_client_id", "xxxxx.apps.googleusercontent.com", "--desktop_client_secret_gcp_secret_name", "flyte-desktop-oauth-client-secret", "--webapp_client_id", "xxxxx.apps.googleusercontent.com", "--project", "project-1"]
  ```               
3. Try to run something like `flytectl get project`

### Screenshots

![image](https://github.com/user-attachments/assets/97ee88e7-f20d-489f-8c22-ee1273f74d4d)

### Are you sure this issue hasn't been raised already?

- [X] Yes

### Have you read the Code of Conduct?

- [X] Yes

**Comment by eapolinario** [comment]
@gverkes , can you confirm that running the `flyte-iap` command separately works?

Also, can you increase the log level in the invocation of `flytectl`? You can set the ` --logger.level` flag to `5`.

**Comment by ademariag** [comment]
Hello, I also working with @gverkes and looking at this again.

I have setup IAP which works fine on the "web" authentication to the flyte console.

I have the following setup

```           appAuth:
                thirdPartyConfig:
                  flyteClient:
                    clientId: flytectl # is this a placeholder or a fixed string??????
                    redirectUri: http://localhost:53593/callback
                    scopes:
                      - offline
                      - all
```

When I try to login, I get the following

```
flytectl get project --logger.level 5                              
{"json":{},"level":"debug","msg":"Config section [admin] updated. Firing updated event.","ts":"2025-02-21T14:13:00+01:00"}
{"json":{},"level":"debug","msg":"Config section [otel] updated. No update handler registered.","ts":"2025-02-21T14:13:00+01:00"}
{"json":{},"level":"debug","msg":"Config section [storage] updated. No update handler registered.","ts":"2025-02-21T14:13:00+01:00"}
{"json":{},"level":"debug","msg":"Config section [root] updated. No update handler registered.","ts":"2025-02-21T14:13:00+01:00"}
{"json":{},"level":"info","msg":"Initialized Admin client","ts":"2025-02-21T14:13:00+01:00"}
{"json":{},"level":"debug","msg":"Request failed due to [rpc error: code = Unauthenticated desc = token parse error id token err: access token err: [JWT_VERIFICATION_FAILED] Could not retrieve bearer token from metadata, caused by: rpc error: code = Unauthenticated desc = Request unauthenticated with Bearer, access token err: [JWT_VERIFICATION_FAILED] Could not retrieve id token from metadata, caused by: rpc error: code = Unauthenticated desc = Request unauthenticated with IDToken]. If it's an unauthenticated error, we will attempt to establish an authenticated context.","ts":"2025-02-21T14:13:05+01:00"}
{"json":{},"level":"error","msg":"Failed to load token related config. Error: failed to initialize token source provider. Err: rpc error: code = Internal desc = server closed the stream without sending trailers","ts":"2025-02-21T14:13:08+01:00"}
{"json":{},"level":"debug","msg":"Successfully loaded token related metadata","ts":"2025-02-21T14:13:08+01:00"}
Error: failed to initialize token source provider. Err: rpc error: code = Internal desc = server closed the stream without sending trailers
{"json":{},"level":"error","msg":"failed to initialize token source provider. Err: rpc error: code = Internal desc = server closed the stream without sending trailers","ts":"2025-02-21T14:13:08+01:00"}
```

flyte-iap seems to return a sensible jwt

```
flyte-iap generate-user-id-token --desktop_client_id XXXXX-gg7igd0bhbh0254gvhkt20e37vfos4t3.apps.googleusercontent.com --desktop_client_secret_gcp_secret_name flyte-iap-secret --webapp_client_id XXXXXX-0m93s0apeij95jlsgv1t6pj9dnp7khqe.apps.googleusercontent.com --project XXXXXXX-research  
/Users/alessandro/.pyenv/versions/3.12.8/lib/python3.12/site-packages/google/auth/_default.py:76: UserWarning: Your application has authenticated using end user credentials from Google Cloud SDK without a quota project. You might receive a "quota exceeded" or "API not enabled" error. See the following page for troubleshooting: https://cloud.google.com/docs/authentication/adc-troubleshooting/user-creds. 
  warnings.warn(_CLOUD_SDK_CREDENTIALS_WARNING)
eyJhbGciOiJSUzI1NiIs[...]kx5C-T6z1goCnObnQJcto3ukHQP-AHAShy
```

I have increased the verbosity to the `flyteadmin` deployment, and this is what I get

```
{"json":{},"level":"info","msg":"Error occurred in NewAccessRequest: invalid_client","ts":"2025-02-21T13:13:58Z"}
{"json":{},"level":"debug","msg":"Running authentication gRPC interceptor","ts":"2025-02-21T13:15:17Z"}
{"json":{},"level":"debug","msg":"Could not retrieve bearer token from metadata rpc error: code = Unauthenticated desc = Request unauthenticated with Bearer","ts":"2025-02-21T13:15:17Z"}
{"json":{},"level":"info","msg":"Failed to parse Access Token from context. Will attempt to find IDToken. Error: [JWT_VERIFICATION_FAILED] Could not retrieve bearer token from metadata, caused by: rpc error: code = Unauthenticated desc = Request unauthenticated with Bearer","ts":"2025-02-21T13:15:17Z"}
{"json":{},"level":"debug","msg":"Could not retrieve id token from metadata rpc error: code = Unauthenticated desc = Request unauthenticated with IDToken","ts":"2025-02-21T13:15:17Z"}
{"json":{},"level":"debug","msg":"Failed to parse ID Token from context. Error: [JWT_VERIFICATION_FAILED] Could not retrieve id token from metadata, caused by: rpc error: code = Unauthenticated desc = Request unauthenticated with IDToken","ts":"2025-02-21T13:15:17Z"}
{"json":{},"level":"debug","msg":"gRPC server info in logging interceptor []method [/flyteidl.service.AuthMetadataService/GetOAuth2Metadata]\n","ts":"2025-02-21T13:15:17Z"}
{"json":{},"level":"debug","msg":"gRPC server info in logging interceptor []method [/flyteidl.service.AuthMetadataService/GetPublicClientConfig]\n","ts":"2025-02-21T13:15:17Z"}
{"json":{},"level":"debug","msg":"gRPC server info in logging interceptor []method [/flyteidl.service.AuthMetadataService/GetPublicClientConfig]\n","ts":"2025-02-21T13:15:17Z"}
{"json":{},"level":"info","msg":"Error occurred in NewAccessRequest: invalid_client","ts":"2025-02-21T13:15:17Z"}
{"json":{},"level":"info","msg":"Error occurred in NewAccessRequest: invalid_client","ts":"2025-02-21T13:15:17Z"}
{"json":{},"level":"info","msg":"Error occurred in NewAccessRequest: invalid_client","ts":"2025-02-21T13:15:32Z"}
{"json":{},"level":"info","msg":"Error occurred in NewAccessRequest: invalid_client","ts":"2025-02-21T13:15:32Z"}
{"json":{},"level":"info","msg":"Error occurred in NewAccessRequest: invalid_client","ts":"2025-02-21T13:15:47Z"}
{"json":{},"level":"info","msg":"Error occurred in NewAccessRequest: invalid_client","ts":"2025-02-21T13:15:47Z"}
{"json":{},"level":"info","msg":"Error occurred in NewAccessRequest: invalid_client","ts":"2025-02-21T13:16:02Z"}
```

**Comment by ademariag** [comment]
The full configuration of our server.yaml

```
    auth:
      appAuth:
        selfAuthServer:
          staticClients:
            flyte-cli:
              grant_types:
              - refresh_token
              - authorization_code
              id: flyte-cli
              public: true
              redirect_uris:
              - http://localhost:53593/callback
              - http://localhost:12345/callback
              response_types:
              - code
              - token
              scopes:
              - all
              - offline
              - access_token
            flytectl:
              grant_types:
              - refresh_token
              - authorization_code
              id: flytectl
              public: true
              redirect_uris:
              - http://localhost:53593/callback
              - http://localhost:12345/callback
              response_types:
              - code
              - token
              scopes:
              - all
              - offline
              - access_token
            flytepropeller:
              client_secret: JDJiJDA2JEVlTUJrOXI5RDZEV2ZJSmXXXXXXXlrbkRLRXhncjJJenpXMzJzQmwu

              grant_types:
              - refresh_token
              - client_credentials
              id: flytepropeller
              public: false
              redirect_uris:
              - http://localhost:3846/callback
              response_types:
              - token
              scopes:
              - all
              - offline
              - access_token
        thirdPartyConfig:
          flyteClient:
            clientId: flytectl
            redirectUri: http://localhost:53593/callback
            scopes:
            - offline
            - all
      authorizedUris:
      - https://flyte.XXXXX.com
      - http://flyteadmin:80
      - http://flyteadmin.flyte.svc.cluster.local:80
      userAuth:
        openId:
          baseUrl: https://accounts.google.com
          clientId: XXXXX-0m93s0apeij95jlsgv1t6pj9dnp7khqe.apps.googleusercontent.com
          scopes:
          - profile
          - openid
    flyteadmin:
      eventVersion: 2
      metadataStoragePrefix:
      - metadata
      - admin
      metricsScope: 'flyte:'
      profilerPort: 10254
      roleNameKey: iam.amazonaws.com/role
      testing:
        host: http://flyteadmin
    server:
      grpc:
        port: 8089
      httpPort: 8088
      security:
        allowCors: true
        allowedHeaders:
        - Content-Type
        allowedOrigins:
        - '*'
        secure: false
        useAuth: true
```
