### ISSUE TITLE
[FlyteCTL Feature] `kubectl`-like configuration from multiple files

### ISSUE THREAD

**Issue by granthamtaylor** [flyteorg/flyte#6237]
### Describe the feature/command for FlyteCTL

Applying multiple configurations can be quite painful, especially over multiple projects / domains.

For example:

`flytectl workflow-execution-config --file manifest.yaml`

```yaml
kind: workflow-execution-config
domain: development
project: protein-design
attributes:
    projectQuotaCpu: "1000"
    projectQuotaMemory: 10Ti
workflow_execution_config:
    security_context:
        run_as: gsa-acme-development@acme.iam.gserviceaccount.com
```

### Provide a possible output or UX example

Instead, one should be able to reference a `yaml` file, or multiple files, or a directory of files, and apply them all simultaneously via `flytectl -f manifest.yaml`

Please see that we are specifying the `kind` in reach file, as opposed to defining it as a CLI arg.

```
---
kind: project
name: protein-design
id: protein-design
---
kind: workflow-execution-config
domain: development
project: protein-design
attributes:
    projectQuotaCpu: "1000"
    projectQuotaMemory: 10Ti
workflow_execution_config:
    security_context:
        run_as: gsa-acme-development@acme.iam.gserviceaccount.com
---
kind: workflow-execution-config
domain: production
project: protein-design
attributes:
    projectQuotaCpu: "2000"
    projectQuotaMemory: 20Ti
workflow_execution_config:
    security_context:
        run_as: gsa-acme-development@acme.iam.gserviceaccount.com
```

This is analogous to how `kubectl` works.

### Are you sure this issue hasn't been raised already?

- [x] Yes

### Have you read the Code of Conduct?

- [x] Yes
