### ISSUE TITLE
[BUG] Configuring cloudEvents with Kafka doesn't produce events nor errors

### ISSUE THREAD

**Issue by davidmirror-ops** [flyteorg/flyte#6402]
### Describe the bug

Environment:
`flytekit: 1.15.3`
`flyte: 1.15.1`
flyte-sandbox
Apache Kafka 4.0.0 with PLAIN authentication (no `SASL`, no `TLS`) running in the same K8s cluster as Flyte

Applying the following configuration:

```
cloudEvents:
  cloudEventVersion: v2
  enable: true
  type: kafka
  kafka:
    version: "4.0.0"
    brokers:
    - kafka-controller-0.kafka-controller-headless.kafka.svc.cluster.local:9092
    - kafka-controller-1.kafka-controller-headless.kafka.svc.cluster.local:9092
    - kafka-controller-2.kafka-controller-headless.kafka.svc.cluster.local:9092
  eventsPublisher:
    eventTypes:
    - all
    topicName: flyte_cloud_events
```

Doesn't produce any effect beyond just adding it to the flyteadmin ConfigMap. 
The `flyte_cloud_events` topic exists in the Kafka instance but despite running multiple executions no message gets there besides what I sent from a test Kafka client:

```
I have no name!@kafka-controller-1:/$ kafka-console-consumer.sh \
            --bootstrap-server kafka.kafka.svc.cluster.local:9092 \
            --topic flyte_cloud_events \
            --from-beginning
hi
This is a test
```

Also there are no WARN or ERROR messages related to cloud events in the Flyte pod.

### Expected behavior

Once configured correctly, one should see execution events coming in the cloudEvents spec format

### Are you sure this issue hasn't been raised already?

- [x] Yes

### Have you read the Code of Conduct?

- [x] Yes
