### ISSUE TITLE
[BUG] Unable to locate credentials

### ISSUE THREAD

**Issue by RonnyLV** [flyteorg/flyte#6415]
### Describe the bug

Getting error from task runners:
```
flytekit.exceptions.system.FlyteDownloadDataException: SYSTEM:DownloadDataError: error=Failed to get data from s3://my-organization-flyte-container/my-project/development/W5U5DH4T6ZCNZJ35P6PZNH3QQU======/fastaa54baa64adba7d1055161ff808bf0a2.tar.gz to ./ (recursive=False).
```

Fresh Helm installation of flyte-binary with following storage configuration:
```
  storage:
    type: stow
    providerConfig:
      s3:
        endpoint: <DO Spaces URL>
        authType: accesskey
        accessKey: <DO Spaces Access Key>
        secretKey: <DO Spaces Secret Key>
        region: <DO Spaces Region>
        disable-ssl: false
```

### Expected behavior

Task can be finished successfully.

### Are you sure this issue hasn't been raised already?

- [x] Yes

### Have you read the Code of Conduct?

- [x] Yes

**Comment by RonnyLV** [comment]
Fixed by adding this inline setting

```
  inline:
    plugins:
      k8s:
        inject-finalizer: true
        default-env-vars:
          - FLYTE_AWS_ENDPOINT: <DO Spaces URL>
          - FLYTE_AWS_ACCESS_KEY_ID: <DO Spaces access key>
          - FLYTE_AWS_SECRET_ACCESS_KEY: <DO Spaces secret key>
```
